### ISSUE TITLE
Request headers not passed to interceptor

### ISSUE THREAD

**Issue by jtwolgamott** [hapifhir/hapi-fhir-jpaserver-starter#10]
I've cloned the latest of this project and added an AuthInterceptor which implements IServerInterceptor. Within the interceptor, I'm currently just printing the request headers, and returning true. I intend to implement custom authentication using JWT within this interceptor once I'm able to get the Authorization header value. Here's my implementation of the incomingRequestPreProcessed method:

```
@Override
public boolean incomingRequestPreProcessed(HttpServletRequest theRequest, HttpServletResponse theResponse) {
        System.out.println("Executing incomingRequestPreProcessed");
        Enumeration headerNames = theRequest.getHeaderNames();
        while (headerNames.hasMoreElements()) {
            String key = (String) headerNames.nextElement();
            String value = theRequest.getHeader(key);
            System.out.println(key + " : " + value);
        }
        String authHeader = theRequest.getHeader("Authorization");
        System.out.println(authHeader); //prints null?
        return true;
}
```

My AuthInterceptor has been registered in JpaRestfulServer as shown below:

```
AuthInterceptor authInterceptor = new AuthInterceptor();
this.registerInterceptor(authInterceptor);
```

I then run the project using `mvn jetty:run` and attempt to make a request to the base URI at http://localhost:8080/hapi-fhir-jpaserver/ using Postman/Curl, etc. with a basic Authorization header set. What I observe is that the Authorization header is null and only the following header values are present in the incomingRequestPreProcessed method, none of which were explicitly set in my request:
```
User-Agent : HAPI-FHIR/3.7.0 (FHIR Client; FHIR 3.0.1/DSTU3; apache)
Accept-Charset : utf-8
Connection : keep-alive
Host : localhost:8080
Accept-Encoding : gzip
Accept : application/fhir+xml;q=1.0, application/fhir+json;q=1.0, application/xml+fhir;q=0.9, application/json+fhir;q=0.9
```

It appears that there's some component within the hapi-fhir system that's stripping off my request headers? Is this the intended behavior, or is there some other approach I should be taking to accomplish my use case of implementing a custom authentication provider?

**Comment by jamesagnew** [comment]
@jtwolgamott There is nothing in the stack that should be stripping headers..

Does the header make it through if you use Postman to create the request?

**Comment by jtwolgamott** [comment]
I see the issue now: I was attempting to access the base URI, rather than an actual FHIR resource - once I request a FHIR resource on the server, i.e., `/fhir/metadata` the interceptor is called and the `Authorization` header is passed through as expected.
