### ISSUE TITLE
Connect  with non relational data base

### ISSUE THREAD

**Issue by jmistry65** [hapifhir/hapi-fhir-jpaserver-starter#105]
How can i connect with non relational database?
Like hadoop.

**Comment by jamesagnew** [comment]
This is addressed here: https://groups.google.com/forum/#!topic/hapi-fhir/Inoqcj3pJ1c

Note, please don't post questions in multiple places at the same time. Please see: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
