### ISSUE TITLE
Next search does not work properly: /HealthcareService_include=HealthcareService:organization:Organization&_revinclude=InsurancePlan:network:Organization

### ISSUE THREAD

**Issue by lytvynenko-dmitriy** [hapifhir/hapi-fhir-jpaserver-starter#106]
**Version:** 
5.0.1

**Description:**
HAPI Jpa Server doesn’t handle next searches properly:
curl -X GET  "https://localhost:8443/hapi-fhir-jpaserver/R4/HealthcareService?_include=HealthcareService:organization:Organization&_revinclude=InsurancePlan:network:Organization" --insecure
curl -X GET  "https://localhost:8443/hapi-fhir-jpaserver/R4/HealthcareService?_include=HealthcareService:organization:Organization&_revinclude:iterate=InsurancePlan:network:Organization" --insecure

**Expected:** 
HAPI returns healthcare services, organizations they reference to and insurance plans which reference to organizations which are referenced by healthcare services. 

**Observed:**
HAPI returns healthcare services and organizations but not insurance plans.

**Comments:**
In code as an entry point I found next method ca.uhn.fhir.jpa.search.PersistedJpaBundleProvider#toResourceList which handles include/revinclude requests in lines 363/364. If I switch these lines, the search works as expected.

**Comment by jamesagnew** [comment]
Those `_include` statements are not correctly formed. Includes have to be in the form `_include=[resourceType]:[paramName]` with no third part. See http://hl7.org/fhir/search.html
