### ISSUE TITLE
Docs for docker container

### ISSUE THREAD

**Issue by ckmaresca** [hapifhir/hapi-fhir-jpaserver-starter#111]
Referencing this [comment](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/68#issuecomment-651367703) about creating better/simpler docs for the docker image located [here](https://hub.docker.com/r/hapiproject/hapi)

**Comment by seanmcilvenna** [comment]
This is done.
https://hub.docker.com/repository/docker/hapiproject/hapi/general
Hopefully this helps.
