### ISSUE TITLE
Dataset and loading data?

### ISSUE THREAD

**Issue by ckmaresca** [hapifhir/hapi-fhir-jpaserver-starter#112]
The current docker images don't seem to have any data.  How does one go about loading data into HAPI-FHIR-JPA for testing?

I know we can create generic data using Synthea but loading it is a mystery.  I have a instance of the docker image running with MySQL, so some pointers would be helpful.....

**Comment by seanmcilvenna** [comment]
Depends on what kind of data you're wanting to load... If it were me, I'd just do some `GET`s on https://hapi.fhir.org/baseR4 and `PUT` them onto your server. Example:
* GET https://hapi.fhir.org/baseR4/Observation?_count=50
* Go through each Observation and:
   * PUT http://your-installation/fhir/Observation/<OBS_ID>

**Comment by jjcosare** [comment]
Please see PR for your reference: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/19

**Comment by psavva** [comment]
@ckmaresca  Please review the response on this issue and close it if you're happy with the answer.
