### ISSUE TITLE
rel_5_1_0 branch not starting jetty server up

### ISSUE THREAD

**Issue by nagacheruvu** [hapifhir/hapi-fhir-jpaserver-starter#116]
After enabling empi true in happy properties. Server is failing with spring bean dependency errors.

please reach me if you need any additional information.

**Comment by tadgh** [comment]
Heya, this PR should address the bean dependency issue. There was a change in the empi-rules.json format which has been fixed. Note that subscriptions still need to be enabled if you want to use EMPI.
