### ISSUE TITLE
how to modify EID system url[Documentation]

### ISSUE THREAD

**Issue by nagacheruvu** [hapifhir/hapi-fhir-jpaserver-starter#119]
Im trying to update EID system url & could not find documentation on how run standalone instance to test EID on my localhost.
please provide documentation on how to modify & run EID system on local host.

Please provide url link to access EMPI resources from FHIR UI. 

For EMPI operations is there any screen in FHIR server ? .

Thanks,
Naga

**Comment by jamesagnew** [comment]
Hi @nagacheruvu  - Please see this wiki page for information on where to ask for help with HAPI FHIR: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
