### ISSUE TITLE
rel_5_1_0 is not starting up

### ISSUE THREAD

**Issue by nagacheruvu** [hapifhir/hapi-fhir-jpaserver-starter#122]
Getting below error when trying to run rel_5_1_0 with latest branch checkout

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'empiSettings' defined in class path resource [ca/uhn/fhir/jpa/starter/EmpiConfig.class]: Unsatisfied dependency expressed through method 'empiSettings' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'ca.uhn.fhir.empi.rules.config.EmpiRuleValidator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
Thanks

**Comment by nagacheruvu** [comment]
Any update would be greatly appreciated.

**Comment by krsatyam01** [comment]
The Issue persists in the latest version, downloaded today.  https://github.com/hapifhir/hapi-fhir-jpaserver-starter/releases/tag/v5.1.0.

**Comment by jamesagnew** [comment]
Thanks for reporting. Fix coming up.

**Comment by jvitrifork** [comment]
@jamesagnew - I removed it in https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/125 due to the fact that it didn't work

**Comment by krsatyam01** [comment]
> Thanks for reporting. Fix coming up.

Thank you for the fix.

**Comment by winne42** [comment]
@jamesagnew Also thx for the fix! When will the images on Docker Hub be updated?

**Comment by winne42** [comment]
@seanmcilvenna could you update the images on Docker Hub, please?

**Comment by pirocraft** [comment]
Got this issue with docker v5.1.0
Workaround pulling v5.0.0
