### ISSUE TITLE
NoSuchBeanDefinitionException at server startup when empi.enabled=false

### ISSUE THREAD

**Issue by j-fbriere** [hapifhir/hapi-fhir-jpaserver-starter#129]
The following exception is thrown at startup when `empi.enabled=false` (which is the default property setting):

`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'ca.uhn.fhir.empi.rules.config.EmpiRuleValidator' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}`

This is due to the **ca.uhn.fhir.jpa.starter.EmpiConfig** component class which is automatically instantiated by the Spring component scanning.
The problem is that the class reference other Spring component classes, and specifically ca.uhn.fhir.empi.rules.config.EmpiRuleValidator, that are instantiated with ca.uhn.fhir.jpa.empi.config.EmpiSubmitterConfig and/or  ca.uhn.fhir.jpa.empi.config.EmpiConsumerConfig component classes.
But those component classes are not instantiated when `empi.enabled=false` (as it should be).
See ca.uhn.fhir.jpa.starter.ApplicationContext.init():
```
  if (HapiProperties.getEmpiEnabled()) {
      register(EmpiSubmitterConfig.class);
      register(EmpiConsumerConfig.class);
      register(EmpiConfig.class);
    }

```
But EmpiConfig is instantiated because of the Spring component scanning.
The scanning is defined in the **ca.uhn.fhir.jpa.config.BaseConfig** component class like this:
```
@ComponentScan(basePackages = "ca.uhn.fhir.jpa", excludeFilters = {
	@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value = BaseConfig.class),
	@ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, value = WebSocketConfigurer.class),
	@ComponentScan.Filter(type = FilterType.REGEX, pattern = ".*\\.test\\..*"),
	@ComponentScan.Filter(type = FilterType.REGEX, pattern = ".*Test.*"),
	@ComponentScan.Filter(type = FilterType.REGEX, pattern = "ca.uhn.fhir.jpa.subscription.*"),
	@ComponentScan.Filter(type = FilterType.REGEX, pattern = "ca.uhn.fhir.jpa.searchparam.*"),
	@ComponentScan.Filter(type = FilterType.REGEX, pattern = "ca.uhn.fhir.jpa.empi.*"),
	@ComponentScan.Filter(type = FilterType.REGEX, pattern = "ca.uhn.fhir.jpa.batch.*")
})
```
All the spring component classes with the base package _ca.uhn.fhir.jpa_ will be instantiated, with some exclusions specified in the definition. But none of the exclusions apply here. Nowhere in this definition is excluded the package _ca.uhn.fhir.jpa.starter_, and since the _EmpiConfig_ component class does not inherit from the _BaseConfig_ component class, the _EmpiConfig_ component class being from the _ca.uhn.fhir.jpa_ base package, it is automatically instantiated.

The solution I found is to refactor the **ca.uhn.fhir.jpa.starter.EmpiConfig** component class to the **ca.uhn.fhir.jpa.empi.config** package, which is excluded from the _ComponentScan_ definition.

Executed on JPA Server version **v5.1.0**

**Comment by fil512** [comment]
Good fix.  Can you submit a PR with that fix?

I'm planning to yank out that @ComponentScan in the coming weeks.  It's caused us no end of trouble.  (I'm the one who added it and I now deeply regret it...)

**Comment by j-fbriere** [comment]
OK I'll submit a PR

**Comment by j-fbriere** [comment]
Jut saw that there already was a fix (the same fix indeed) on the master branch. See issue #122.

I don't have the rights to do a PR.

Here is the patch for this isssue on v5.1.0 :
[fix-129.patch.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/5204981/fix-129.patch.txt)

**Comment by j-fbriere** [comment]
It seems to me that there should be a **v5.1.1** release with at least that fix because right now with the **v5.1.0** release, the server doesn't start without a modification in the code (or activate EMPI but then it requires other modifications in the empi-rules.json file.

**Comment by desjob** [comment]
> It seems to me that there should be a v5.1.1 release with at least that fix because right now with the v5.1.0 release, the server doesn't start without a modification in the code (or activate EMPI even if not needed, but then it requires other modifications in the empi-rules.json file for the server to start).

Agree, can this be shipped?

**Comment by jvitrifork** [comment]
@fil512 With accept of https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/140, the componentScan on packages is removed. It however depends on the deployment method whether the empi is picked up or not - eg. for Spring Boot execution no extra exclude is required.

**Comment by desjob** [comment]
please note that a new version of "latest" AND "v5.1.0" has been shipped on docker hub:
https://hub.docker.com/r/hapiproject/hapi/tags

This issue no longer occurs there, so i think it can be closed!
