### ISSUE TITLE
How to remove the path prefix "hapi-fhir-jpaserver" when deploying via Docker

### ISSUE THREAD

**Issue by awesome-manuel** [hapifhir/hapi-fhir-jpaserver-starter#130]
The webapp is always installed as `hapi-fhir-jpaserver.war`, so tomcat adds this as a path prefix.
I tried overwriting it via `/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml`, but this does not work since `hapi-fhir-jpaserver.war` is deployed in the folder `webapps`.

Is there any other solution to achieve this?

**Comment by j-fbriere** [comment]
Change the Dockerfile like this:
```
RUN rm -R /usr/local/tomcat/webapps/ROOT
COPY --from=build-hapi /tmp/hapi-fhir-jpaserver-starter/target/hapi-fhir-jpaserver.war /usr/local/tomcat/webapps/ROOT.war
```

**Comment by jvitrifork** [comment]
see #137

**Comment by psavva** [comment]
I suggest this issue should be closed
