### ISSUE TITLE
mvn install takes really long!

### ISSUE THREAD

**Issue by sidharthramesh** [hapifhir/hapi-fhir-jpaserver-starter#131]
Is it normal for the `mvn dependency:go-offline` step to take about an hour? Seems like it's downloading the whole internet.

**Comment by jamesagnew** [comment]
Please don't open tickets to ask questions about HAPI FHIR. The following link has details on where to ask questions: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
