### ISSUE TITLE
Unable to deploy hapi-fhir-jpaserver.war on external web container (Tomcat)

### ISSUE THREAD

**Issue by mdivya10** [hapifhir/hapi-fhir-jpaserver-starter#133]
Using mvn clean install I have build the hapi fhir jpaserver starter project and copied hapi-fhir-jpaserver.war in the webapps directory of Tomcat. My Tomcat runs on port 8080 and while trying to access the url http://localhost:8080/hapi-fhir-jpaserver/ it gives 404 error.  On checking Tomcat Manager app the running status for hapi-fhir-jpaserver project is false and on trying to start it I get error message FAIL - Application at context path /hapi-fhir-jpaserver could not be started.

I am able to run server using Maven and using command "mvn -Djetty.port=8888 jetty:run" but I want to deploy the project on external Web container(Tomcat)

Is there some configuration changes that I need to make to deploy on an external web container like Tomcat?

![error](https://user-images.githubusercontent.com/71247611/93048129-c5503600-f67b-11ea-8226-c9500679b7f5.png)
![error1](https://user-images.githubusercontent.com/71247611/93048282-26780980-f67c-11ea-9922-f48a6c8bc37e.png)

**Comment by jamesagnew** [comment]
Hi @mdivya10 - Please don't use GitHub issues to ask questions, see this wiki for a list of the resources available for asking questions and getting help: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
