### ISSUE TITLE
How to change the server url

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir-jpaserver-starter#137]
Hi guys,

first of all thanks a lot for the amazing starter image. 
I really love the HAPI project and the simplicity of providing a ready to run docker file.

I played  around with the project during the last days and were successful to set it up on our k8s cluster.
However I was not able to change the default server_url with the new application.yaml file.

Is there any new attribute that needs to be changed?

I would love to serve the REST API on sth like  https://api.fhir.example.com/ is that possbile?

**Comment by jvitrifork** [comment]
sure - thats possible. See eg. https://www.baeldung.com/tomcat-root-application or use the methods at https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/140/files#diff-04c6e90faac2675aa89e2176d2eec7d8R103 or https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/140/files#diff-04c6e90faac2675aa89e2176d2eec7d8R118

**Comment by ZuSe** [comment]
Thanks. Which of the options is best in regards to performance and stability?
We deploy to kubernetes so the dockerfile is basically the easiest, but I don't mind build it around google distro-less if brings any great benefits over a tomcat base image.

**Comment by jvitrifork** [comment]
distroless has a lower foot print and is more secure. Take a read on it ie. https://medium.com/better-programming/how-to-harden-your-containers-with-distroless-docker-images-c2abd7c71fdb.

**Comment by ZuSe** [comment]
Thanks. Would you mind changing the default Dockerfile accordingly? 
We should provide people a ready to run project.
A working Dockerfile makes k8s-deployment very easy and can help client developers to spawn it quickly in any of their sandbox cloud envs

**Comment by jvitrifork** [comment]
There should be no problem in making distroless the default in the Dockerfile, I would however value input for that decision from @seanmcilvenna and @jamesagnew

**Comment by seanmcilvenna** [comment]
I'm not particularly familiar with "distroless" images... I get the concept based on that medium.com article, though. My chief concern is: HAPI is still very much under development, and often requires doing a little digging to figure out what's wrong. With a distroless image, the image may not contain the tools necessary to debug issues. Any thoughts on that?

**Comment by jkiddo** [comment]
Generally, IMHO, you shouldn't debug much inside a docker container - the intention with docker is to isolate and streamline the setup, as well as keeping things as immutable as possible. Also, I consider HAPI stable - stable enough to build highly customized national solutions on top of it. If you need to debug the HAPI FHIR starter, then spin up the Spring Boot setup. Debugging can then be done inside the comfort of your IDE. An alternative is using https://github.com/GoogleContainerTools/distroless#debug-images.
@ZuSe if you wan't to experiment with distroless, you can just build the image yourself doing

`mvn clean package com.google.cloud.tools:jib-maven-plugin:dockerBuild -Dimage=distroless-hapi` and then push it to whatever docker repo you like

**Comment by jkiddo** [comment]
FYI jkiddo==jvitrifork

**Comment by seanmcilvenna** [comment]
@jkiddo that's a nice theory about not having to dig into the docker container... All I can say, is that I've had to do that many times. I'm pretty good at finding corner-case issues, though, as @jamesagnew will probably attest.

**Comment by jkiddo** [comment]
@seanmcilvenna I'm sure you are good at finding corner cases. All I can say is that I don't consider it an option to be able to step inside a container (that would be a security vulnerability and not an option in most (if not all) of my k8s setups) - because it should not be anything else than the environment that you spec'ed and the application you deployed inside it - and both should usually be within reach in your dev environment. Have you to this date found any bugs that related to the fact that in ran inside docker?
That said, whether or not this project runs in distroless or not should not be that big a deal. To me this project is for exemplifying how HAPI FHIR can be used. It is not fit for production in any sense as it has not security mechanisms and no business customization inside it - hence I really have no opinion to whether it should default to be deployed in eg. tomcat, jetty, wildfly or a distroless spring boot all inside docker. That is also why the documentation now states 4 different ways to run it.

**Comment by ZuSe** [comment]
I totally agree with @jkiddo.
It's basically forbidden for all our k8s-pods to use them for debugging.
Only very limited people have access to it. Everybody that needs to debug can run it manually or quickly create a debug build.

Just to make clear, i would love to use the distroless as part of the Dockerfile. Right now I am using simple spring boot. Background is that we are using Gitlab CI for deployment and it aims for a Dockerfile in each project (then the magic works). Everything else would be overhead to maintain and make the fhir server different from the other containers.

My quick solution for now:
`FROM maven:3.6.3-jdk-11-slim as build-hapi
WORKDIR /tmp/hapi-fhir-jpaserver-starter

COPY pom.xml .
RUN mvn -ntp dependency:go-offline

COPY src/ /tmp/hapi-fhir-jpaserver-starter/src/
RUN mvn clean package spring-boot:repackage -Pboot

EXPOSE 8080

CMD java -jar target/ROOT.war`

**Comment by jvitrifork** [comment]
@ZuSe 
It could look like this - then you run both spring boot AND distroless:

```
FROM maven:3.6.3-jdk-11-slim as build-hapi
WORKDIR /tmp/hapi-fhir-jpaserver-starter

COPY pom.xml .
RUN mvn -ntp dependency:go-offline

COPY src/ /tmp/hapi-fhir-jpaserver-starter/src/
RUN mvn clean package spring-boot:repackage -Pboot

FROM gcr.io/distroless/java:11

COPY --from=build-hapi /tmp/hapi-fhir-jpaserver-starter/target/ROOT.war /app/main.jar

EXPOSE 8080
WORKDIR /app
CMD ["main.jar"]
```

**Comment by jvitrifork** [comment]
@ZuSe please close the issue if you are satistfied with the current solution. I've created the PR  https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/145 that contains the above adjustments.

**Comment by psavva** [comment]
@ZuSe   If you're OK with the solution, please can you go ahead and close this issue?
