### ISSUE TITLE
Cannot write into index directory: target\lucenefiles for index ca.uhn.fhir.jpa.model.entity.ResourceIndexedSearchParamString

### ISSUE THREAD

**Issue by Viroopi** [hapifhir/hapi-fhir-jpaserver-starter#150]
Recalled

**Comment by ricardofago** [comment]
Probably related to #152. Judging by https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/EnvironmentHelper.java, it looks like the `hibernate.search.default.indexBase` property is currently hardcoded, so either recompile changing it accordingly or run Tomcat with privileges to recreate/write to `target\lucenefiles`.

**Comment by Viroopi** [comment]
recalled
