### ISSUE TITLE
Resource ID creation automatic?

### ISSUE THREAD

**Issue by JoeMcCaffrey** [hapifhir/hapi-fhir-jpaserver-starter#151]
Hi - I have partitions enabled. When I create a resourse on the server it assigns it an id value and ignores the one that I submitted. Can this be turned off? Is this expected?

POST - http://localhost:8080/fhir/PARTITION-123/Patient/

```{
    "resourceType": "Patient",
    "id": "1111",
    "gender": "male",
    "contact": {
        "gender": "male"
    }
}

response:
{
  "resourceType": "Patient",
  "id": "107",
  "meta": {
    "versionId": "1",
    "lastUpdated": "2020-10-09T10:22:16.917-04:00"
  },
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table class=\"hapiPropertyTable\"><tbody/></table></div>"
  },
  "gender": "male",
  "contact": [
    {
      "gender": "male"
    }
  ]
}```

**Comment by jamesagnew** [comment]
When using a POST, the server is required to assign an ID and ignore any in the resource body, per the FHIR spec.

You need to use a PUT and include the ID in the URL as well in order to do a create-with-client-assigned-ID.

Note that by default purely numeric IDs with no letters in them (e.g. `123`) can not be client assigned, but this is configurable.

**Comment by jamesagnew** [comment]
Also, please bring any further discussion to the HAPI FHIR google group as opposed to using GitHub Issues. See this page for more information: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help

**Comment by JoeMcCaffrey** [comment]
Thank you for the quick response!

**Comment by da-baranov** [comment]
I also need to keep client-assigned resource ids in a format of UUIDs. 
For that I changed the AppProperties.client_id_strategy field default value to ANY, then rebuilt, and it works, but such an approach is brute. How could I do the same using application.yaml config file?
