### ISSUE TITLE
What to set as daoconfig_client_id_strategy to enable UUID support

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir-jpaserver-starter#153]
Hi guys,

unfortunately I could not find anything the config. 
What do we need to set in application.yaml to use UUID instead of longs for the default ID generation of FHIR resources?

@jvitrifork I think you introduced that setting? I know how to overwrite it within Java but config params are always the cleaner way.

Best
Patrick

**Comment by jkiddo** [comment]
See https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/5c4a51601f1d113247cb39b918bead878603fd0f/src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java#L346

**Comment by jvitrifork** [comment]
@ZuSe

**Comment by ZuSe** [comment]
@jvitrifork  I set it to ANY, but it does not make the server to use uuids for the creation. In the comment of the file it is mentioned but I don't find any appropriate settings for that in application.yaml

**Comment by ZuSe** [comment]
@jvitrifork  
Hi Jens, i think you mean defaulting to UUID is NOT part of it right? Otherwise no PR would be required.
I am not that familiar with Java, but maybe I can hack something :D

**Comment by jvitrifork** [comment]
Correct

**Comment by ZuSe** [comment]
I am not sure if its working proably.
I have set both in code now:

```
  @Override
  protected void initialize() throws ServletException {
    super.initialize();

    // Add your own customization here
    this.registerInterceptor(new IatrosAuthInterceptor());
    this.daoConfig.setResourceClientIdStrategy(DaoConfig.ClientIdStrategyEnum.ANY);
    this.daoConfig.setResourceServerIdStrategy(DaoConfig.IdStrategyEnum.UUID);
  }
```
When I create a new record with my client it force generations an ID on the server. According to the code docs this should not happen. Also, dao_setting is set to strategy 2 in application.yml. Any idea what can be the problem? 
```

curl -L -X POST 'http://localhost:8080/fhir/Patient' \
-H 'Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxOTM4NTIwNjE0LCJqdGkiOiI3NTg1NGM0OTI4YmU0YmZkYWEzMzVkNWI0N2VjYTRhOCIsInVzZXJfaWQiOiIxMTExMTExMS0yMjIyLTMzMzMtNDQ0NC01NTU1NTU1NTU1NTUiLCJpc3MiOiJodHRwczovL2NsaWVudDEuaS1hdHJvcy5vcmcifQ.qo9Y71eYxRYfUyNST3VZ43oA48wDQKkLSfQXzUyQMihylks10e0g5GwsdbolMoHFqk-QH9cuKLpHYmpE_LAOGhwAfgx9Em9OBjQlIMzGQQZlfWsD4YH88Ssqg1qG8EUOWGBdKez0jpYMjYtlsxHQfUlC-e5Gi1SLeRVO0JYn8GY' \
-H 'Content-Type: application/json' \
--data-raw '{
  "resourceType": "Patient",
  "id": "8e9ece1c-dd7d-11ea-b18e-6e8e65aa9911",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">\n      \n      <p>Patient Donald DUCK @ Acme Healthcare, Inc. MR = 654321</p>\n    \n    </div>"
  },
  "identifier": [
    {
      "use": "usual",
      "type": {
        "coding": [
          {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR"
          }
        ]
      },
      "system": "urn:oid:0.1.2.3.4.5.6.7",
      "value": "654321"
    }
  ],
  "active": true,
  "name": [
    {
      "use": "official",
      "family": "Donald",
      "given": [
        "Duck"
      ]
    }
  ],
  "gender": "male"
}'
```

returns

```
{
    "resourceType": "Patient",
    "id": "d731486d-f84e-444d-9dcb-22633cc93446",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2020-11-26T17:35:04.019+01:00"
    },
```
