### ISSUE TITLE
Container accessible from host machine

### ISSUE THREAD

**Issue by WoutV** [hapifhir/hapi-fhir-jpaserver-starter#154]
I am running the FHIR server in a container, but I mapped the ports, because 8080 is already in use by an other application. 
I am now unable to access the resources stored on the server (I am using the `fhirclient` python package). It seems like the mapping is only done for the web app, and not for the API.

**Comment by psavva** [comment]
There is no difference between the web and api. Both are running under the single port 8080.

Provide your dockerfile and assuming docker compose file for analysis

**Comment by psavva** [comment]
Hi @WoutV 

Have you resolved this issue? Can we close this one off?

**Comment by WoutV** [comment]
It can be closed. Its working fine now.
