### ISSUE TITLE
package loader skips unknown package versions without error

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir-jpaserver-starter#158]
When adding a fhir package to the yaml file with an incorrect version no error is thrown.

to reproduce:
```
 implementationguides:
      -  name: KBV.Basis
          version: 1.1.0
```
It just shows: 0 StrucDefs loaded, 0 NamingSystem, etc...

**Comment by jkiddo** [comment]
@patrick-werner not-matching IG's are now rejected and the process is halted during startup if the version does not match
