### ISSUE TITLE
Failed to generate snapshot

### ISSUE THREAD

**Issue by Milzor** [hapifhir/hapi-fhir-jpaserver-starter#166]
I'm running the hapi-fhir-jpaserver-starter locally with DSTU3 and spring-boot. Unfortunately a validation request fails to succeed. I'm using external custom resources from https://simplifier.net/nictizstu3-zib2017. Below example contains the hapi.fhir.org DSTU3 base but in my case, I've loaded all the external custom resources and execute the same validation. The same error occurs. Any clue?

`POST http://hapi.fhir.org/baseDstu3/Condition/$validate`
```
<Condition xmlns="http://hl7.org/fhir">
    <id value="zwangerschap" />
    <meta>
        <profile value="http://nictiz.nl/fhir/StructureDefinition/zib-Pregnancy" />
    </meta>
    <clinicalStatus value="active" />
    <code>
        <coding>
            <system value="http://snomed.info/sct" />
            <code value="364320009" />
            <display value="Pregnancy observable (observable entity)" />
        </coding>
    </code>
    <subject>
        <reference value="urn:uuid:f087e54c-8629-11ea-3978-020000000000" />
        <display value="Leegwater" />
    </subject>
    <context>
        <reference value="EpisodeOfCare/EpisodeOfCare-id" />
    </context>
</Condition>
```

And the result is:

```
<OperationOutcome
  xmlns="http://hl7.org/fhir">
  <text>
    <status value="generated"/>
    <div
      xmlns="http://www.w3.org/1999/xhtml">
      <h1>Operation Outcome</h1>
      <table border="0">
        <tr>
          <td style="font-weight: bold;">ERROR</td>
          <td>[]</td>
          <td>
            <pre>Failed to generate snapshot</pre>
          </td>
        </tr>
      </table>
    </div>
  </text>
  <issue>
    <severity value="error"/>
    <code value="processing"/>
    <diagnostics value="Failed to generate snapshot"/>
  </issue>
</OperationOutcome>
```

**Comment by jvitrifork** [comment]
This question is probably more a HAPI FHIR core question or a question for your profile: http://nictiz.nl/fhir/StructureDefinition/zib-Pregnancy

**Comment by Milzor** [comment]
Maybe. hapi-fhir-jpa-server-starter provides loading implementation guides. In fact, the starter fails to load the profile assuming the profile is correct.

**Comment by jvitrifork** [comment]
If the starter fails to load the profile, its probably because of a bug in the profile which is not a HAPI FHIR starter issue.

**Comment by ZuSe** [comment]
@jvitrifork  you are right. I think we can close the issue over here
