### ISSUE TITLE
MySQL database backend fails

### ISSUE THREAD

**Issue by mpieters** [hapifhir/hapi-fhir-jpaserver-starter#17]
I followed the example in the `readme.md` without success, Since we use innodb I changed the dialect to `hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect` and still no success:

**Caused by: java.sql.SQLSyntaxErrorException: Specified key was too long; max key length is 1000 bytes**

```
o.h.t.s.i.ExceptionHandlerLoggedImpl [ExceptionHandlerLoggedImpl.java:27] GenerationTarget encountered exception accepting command : Error executing DDL "create index IDX_SP_URI_RESTYPE_NAME on HFJ_SPIDX_URI (RES_TYPE, SP_NAME)" via JDBC Statement
```
```
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create index IDX_SP_URI_RESTYPE_NAME on HFJ_SPIDX_URI (RES_TYPE, SP_NAME)" via JDBC Statement
```

This is far from my expertise and I have no idea how to dive deeper into this issue to provide some more useful information

**Comment by mpieters** [comment]
Got it working, sorry for the Issue! For others with the same issue(s):

MySQL using `InnoDB` storage engine with `utf8_general_ci`

snippet `hapi.properties`:
```ini
[...]
datasource.driver=com.mysql.jdbc.Driver
datasource.url=jdbc:mysql://prd-mysql:3306/hapi_dstu3?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf8
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
datasource.username=user
datasource.password=secret
hibernate.format_sql=true
hibernate.show_sql=true
[...]
```

**Comment by snimmagadda1** [comment]
Hey I know this is closed but wondering how you figured out the above - I'm trying to startup this example (the spring-boot-jpa) and am running into `SQLSyntaxErrorExceptions` similar to the above on startup [here](https://github.com/jamesagnew/hapi-fhir/tree/master/hapi-fhir-spring-boot/hapi-fhir-spring-boot-samples/hapi-fhir-spring-boot-sample-server-jpa). I have a similar setup but can't figure out why the above won't startup...
