### ISSUE TITLE
ca.uhn.fhir.jpa.starter.EnvironmentHelper Missing Default Property for "hibernate.dialect"

### ISSUE THREAD

**Issue by KevinDougan-SmileCDR** [hapifhir/hapi-fhir-jpaserver-starter#173]
The class ca.uhn.fhir.jpa.starter.EnvironmentHelper sets up some default properties when they cannot be found in the environment.
It sets 12 jpa properties but there are actually 13 that should be set, as the one for "hibernate.dialect" was omitted from this class.

**Comment by jvitrifork** [comment]
Dialect is automatically computed here: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/JpaHibernateDialectProvider.java

**Comment by jvitrifork** [comment]
@KevinDougan-SmileCDR with your change in the code you now effectively forces users to specific the dialect if they were to change any of the other default properties, instead of letting the dialect being automatically detected

**Comment by KevinDougan-SmileCDR** [comment]
Hi @jvitrifork,
I Closed the MR as I was not aware that you had added an auto-detecting Dialect feature.
