### ISSUE TITLE
Where and how can I modify ResourceProvider output?

### ISSUE THREAD

**Issue by pranithan-kang** [hapifhir/hapi-fhir-jpaserver-starter#175]
Hi anyone,

I would like to implement the hapi-fhir-jpasever-starter under this conditions:

### Data Concealing
I have to conceal the data of the resource output. For example, Patient Resource, the steps I would like to do are:
1. Get the output from the original RestfulPatientResourceProvider
2. Modify the output Identifier by

``` Java
MessageDigest digest = MessageDigest.getInstance("SHA-256");
patient.getIdentifier().forEach(iden -> {
    String saltedIden = iden.getValue() + "ALPHA_NUM_STR";
    String hashedIden = Hex.encodeHexString(
        digest.digest(
            saltedIden.getBytes(StandardCharsets.UTF_8)));
    iden.setValue(hashedIden);
});
```

3. Return them as an original RestfulPatientResourceProvider result.

### 6-month-back data
I have to compose new ResourceProvider whichs limit to 6-month-back data. For example, I would like to get the Document Bundle that comprise of the resources that the date is back to 6 months only.

### My questions
What should I do? if it is Reading the document, which document?
Which place in the sourcecode should I start to do my job?
How should I do this, I mean which method such as to inherit Original classes or to compose new things?

Please, suggest me. Any responses are welcomed.

Thank you in advance,

**Comment by jamesagnew** [comment]
Hi @pranithan-kang , please don't create github tickets to ask questions. See here for information: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
