### ISSUE TITLE
SqlExceptionHelper ORA-00907: Missing right parenthesis

### ISSUE THREAD

**Issue by jotorren** [hapifhir/hapi-fhir-jpaserver-starter#176]
Hi,
When using Oracle as persistence database the following error raises at startup:

> [main] TRACE c.u.f.j.s.b.sql.SearchQueryExecutor [SearchQueryExecutor.java:120] About to execute SQL: select * from ( SELECT RES_ID FROM ( SELECT t0.RES_ID FROM HFJ_RESOURCE t0 WHERE ((t0.RES_TYPE = ?) AND (t0.RES_DELETED_AT IS NULL)) )  AS RES_ID ) where rownum <= ?
[main] WARN  o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:137] SQL Error: 907, SQLState: 42000
[main] ERROR o.h.e.jdbc.spi.SqlExceptionHelper [SqlExceptionHelper.java:142] ORA-00907: Missing right parenthesis

The source of the problem is the `SearchQueryBuilder` class , where you can find:

```sql = "SELECT " +
	myFirstPredicateBuilder.getResourceIdColumn().getColumnNameSQL() +
	" FROM ( " + sql + " ) " +
	" AS " + myFirstPredicateBuilder.getResourceIdColumn().getColumnNameSQL();
```

The solution should be to remove the " `AS`" word (at least for Oracle)

Thanks

**Comment by jvitrifork** [comment]
@jamesagnew that one is for you

**Comment by jamesagnew** [comment]
Thanks @jotorren, I'll investigate this today.

**Comment by jamesagnew** [comment]
@jotorren This is fixed in HAPI FHIR master now. Are you able to bump your starter project to using HAPI FHIR 5.3.0-SNAPSHOT and verify?

**Comment by jotorren** [comment]
> @jotorren This is fixed in HAPI FHIR master now. Are you able to bump your starter project to using HAPI FHIR 5.3.0-SNAPSHOT and verify?

Sure, thanks a lot. I'll inform you about the result
