### ISSUE TITLE
Make Narrative Generation configurable through application.yaml

### ISSUE THREAD

**Issue by patrick-werner** [hapifhir/hapi-fhir-jpaserver-starter#182]
Narrative Generation is currently enabled and hardcoded. The Narrative Generator throws still Exceptions on several Resources, this breaks transactions a lot of time.

Proposal to solve that:
Make Narrative Generation configurable through application.yaml

**Comment by vladonemo** [comment]
The #183 adds this configuration property:
`hapi.fhir.narrative_enabled`

**Comment by vladonemo** [comment]
@patrick-werner does it work for you?

**Comment by jvitrifork** [comment]
@vladonemo your PR is now merged by @patrick-werner
