### ISSUE TITLE
Additional servlets do not work when websocket subscriptions are enabled

### ISSUE THREAD

**Issue by blangley28** [hapifhir/hapi-fhir-jpaserver-starter#192]
When `subscription.websocket.enabled` is set to true additional servlets cannot be reached. They do start up correctly but any attempt to hit those endpoints results in a 404. As soon as the configuration is set to false it begins working again.

Steps to reproduce:

1. Add a new servlet to `web.xml`
2. Define the servlet Spring RestController
3. Run the server and test the servlet works
4. In `hapi.properties` set `subscription.websocket.enabled=true`
5. Run the server again and the servlet doesn't work

**Comment by jvitrifork** [comment]
@blangley28 there is no web.xml in this project
