### ISSUE TITLE
ModelConfig bean

### ISSUE THREAD

**Issue by henrym6003** [hapifhir/hapi-fhir-jpaserver-starter#2]
Hi @jamesagnew, thanks for everything you do.

I tried running locally with `mvn jetty:run`.  However, was receiving the below error during context loading:

```
2019-01-17 17:31:02.319 [main] ERROR o.s.web.context.ContextLoader [ContextLoader.java:312] Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'matchResourceUrlService': Unsatisfied dependency expressed through field 'myMatchUrlService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'matchUrlService': Unsatisfied dependency expressed through field 'mySearchParamRegistry'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'searchParamRegistry': Unsatisfied dependency expressed through field 'myModelConfig'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'ca.uhn.fhir.jpa.model.entity.ModelConfig' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

To resolve, I added the below to FhirServerConfig.java 

```
	@Bean
	public ModelConfig modelConfig() {
		return daoConfig().getModelConfig();
	}
```

**Comment by henrym6003** [comment]
This only appears to be an issue for `<version>3.7.0-SNAPSHOT</version>`

Downgrading to  `<version>3.6.0</version>` did not require the ModelConfig

**Comment by seanmcilvenna** [comment]
The code you suggested was added to the project, and I don't believe this is an issue any more. I am building against 3.7.0 from my environment(s) just fine, now. Let me know if I am wrong and need to re-open the issue.

**Comment by ytecle** [comment]
Hello, the error that I am getting seems to be similar to the error posted by Henry, I applied his solution but I am still getting an error, can someone tell what the error below might be ?


2020-06-24 12:06:59.433 [main] INFO  o.s.o.j.LocalContainerEntityManagerFactoryBean [AbstractEntityManagerFactoryBean.java:598] Closing JPA EntityManagerFactory for persistence unit 'default'
2020-06-24 12:06:59.523 [main] ERROR o.s.web.context.ContextLoader [ContextLoader.java:313] Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'daoResourceLinkResolver': Unsatisfied dependency expressed through field 'myIdHelperService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'idHelperService': Unsatisfied dependency expressed through field 'myForcedIdDao'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'IForcedIdDao': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Not a managed type: class ca.uhn.fhir.jpa.model.entity.ForcedId
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)


Thank you,
