### ISSUE TITLE
Build and publish the container images using GitHub Actions

### ISSUE THREAD

**Issue by chgl** [hapifhir/hapi-fhir-jpaserver-starter#205]
It would be great if the container images were automatically build and pushed to Docker Hub (Maybe GHCR.io in the future as well?).

I've taken a stab at it here: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/compare/master...chgl:master

This builds a new image whenever there's a commit to master, tagged as `master` and `sha-<commit-hash>`. Whenever there's a new release, an image tagged as e.g. `v5.3.0` is build from the corresponding git tag. Because I am a big fan of distroless containers, each tag also has a `-distroless` flavor where the final base image is `gcr.io/distroless/java:11`, which required adding a new distroless-build stage to the Dockerfile.

If this is something you are interested in, I can assist you in setting it up. I'll create a new PR with the changes and then all that is needed is creating a GitHub repo secret `DOCKERHUB_USERNAME` with the `hapiproject` Docker Hub user and `DOCKERHUB_TOKEN` with a token created via https://docs.docker.com/docker-hub/access-tokens/.

**Comment by jvitrifork** [comment]
@chgl  Definitely make a PR on this one. It sounds great
