### ISSUE TITLE
Helm chart for installing on Kubernetes

### ISSUE THREAD

**Issue by chgl** [hapifhir/hapi-fhir-jpaserver-starter#206]
I've recently created a Helm chart to make it easier to install the HAPI FHIR server on Kubernetes:

https://github.com/chgl/charts/tree/master/charts/hapi-fhir-jpaserver

My main question is if there's interest in including this chart in the `hapi-fhir-jpaserver-starter` repo? Over at https://github.com/chgl/charts I am using https://github.com/helm/chart-releaser to host Helm charts using GitHub pages. Something similar could be set-up in this repo, or a dedicated `hapifhir/charts` repo could be created. 

Of course if there are no plans to officially support any Kubernetes/Helm installation, then that's perfectly fine too!

**Comment by jvitrifork** [comment]
Make a PR, and we'll have a look. @jamesagnew - I believe the charts would be a proper fit for this repo.

**Comment by jamesagnew** [comment]
I'm definitely in favour, I certainly assume this would be useful to others.

TBH I don't think I'd be qualified to review it though, @jvitrifork do you know enough about these for that? 

I can help get it set up on GitHub pages though..

**Comment by jvitrifork** [comment]
I have a colleage of mine who would be qualified ;)
