### ISSUE TITLE
HAPI FHIR Mongo Support

### ISSUE THREAD

**Issue by fhiruser** [hapifhir/hapi-fhir-jpaserver-starter#211]
Team,  Can you please let us know if the hapi-fhir-jpaserver-starter server supports direct FHIR resource persistence into MongoDB similar to the embedded H2 or external MySQL databases. Thanks.

**Comment by jamesagnew** [comment]
Hi @fhiruser - This project requires a relational database, so MongoDB is not supported.

There is a MongoDB storage module available through the commercial Smile CDR distribution: https://smilecdr.com/docs/fhir_repository/fhir_storage_mongodb_module.html

I have also certainly heard of many people successfully using the HAPI FHIR plain server framework to roll a MongoDB based FHIR server.
