### ISSUE TITLE
Can't resolve the 404 error

### ISSUE THREAD

**Issue by krisdas73** [hapifhir/hapi-fhir-jpaserver-starter#213]
I have build the module in IntelliJ and have the ROOT.war file. Deployed the WAR in Apache Tomcat, and while accessing http://localhost:8080/fhir/metadata, I am getting:

HTTP Status 404 – Not Found
Type Status Report

Message The requested resource [/fhir/metadata] is not available

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Do I need to update any source code or configuration? Thankn you.

**Comment by shubhamparikh927** [comment]
Can you try with below path, I also face the same problem 
http://localhost:8080/ROOT/fhir/metadata

**Comment by KevinDougan-SmileCDR** [comment]
Try this:

http://localhost:8080/metadata

**Comment by krisdas73** [comment]
Tried both, but still same issue.

**Comment by krisdas73** [comment]
Under the http://localhost:8080/manager/html/, I can see the following:

Path: /
Version:None Specified

Any idea, why it is not showing? It got deployed.

**Comment by jkiddo** [comment]
The Dockerfile actually deploys the war file to Tomcat (https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/Dockerfile#L28). I don't see any errors when running the service from Docker @krisdas73

**Comment by fragaLY** [comment]
Could you please share your configurations?

**Comment by RafiqueMohammed** [comment]
I am facing the same issue. I just pulled the docker and ran the command.. server is up but I am seeing 404 no matter what resource endpoint or /metdata i try.
Check the screenshot 
![image](https://user-images.githubusercontent.com/3153288/133605293-b52a5af3-cb87-4662-aa52-f41450ed2c75.png)

and in CLI i have noticed this. Some class format Exception :
 
![image](https://user-images.githubusercontent.com/3153288/133605413-a3234677-219e-4e81-a04f-b60c319ecf70.png)

**Comment by dinipc** [comment]
Hi, I am facing the same issue. I can run the application locally with Jetty and Spring Boot. However after I do a clean build with "mvn clean install" and drop the ROOT.war to webapps in Tomcat, I keep getting the 404. I am deploying it to the root in Tomcat so I am guessing I do not need to any configurative changes in any of the files. 

Does anyone have a resolution?

**Comment by jkiddo** [comment]
Closing as stale
