### ISSUE TITLE
The test cases failed since commit c070429698b820d41724e4278b9a594368f30db5

### ISSUE THREAD

**Issue by frankjtao** [hapifhir/hapi-fhir-jpaserver-starter#218]
All test cases are failed since EnvironmentHelper.java is changed in the above commit by @ttntrifork/@jvitrifork
 can you have a look?

Otherwise I will restore EnvironmentHelper.java

**Comment by jamesagnew** [comment]
@jvitrifork

**Comment by jvitrifork** [comment]
Yep - looking at it
