### ISSUE TITLE
No Docker Hub release for v5.3.0

### ISSUE THREAD

**Issue by rcrichton** [hapifhir/hapi-fhir-jpaserver-starter#221]
There doesn't appear to be a v5.3.0 tag on Docker Hub - https://hub.docker.com/r/hapiproject/hapi/tags?page=1&ordering=last_updated

There is a v5.4.0 tag. However, I don't know what that might refer to as there is no v5.4.0 release tagged in this repo.

![image](https://user-images.githubusercontent.com/266576/112609507-44d97180-8e24-11eb-82a1-8fbb3fe39d01.png)

**Comment by iamonkara** [comment]
I am wondering the exact same thing. @jamesagnew @jvitrifork @seanmcilvenna any idea?

**Comment by citizenrich** [comment]
This appears fixed. For more info see the FHIR chat.
https://hub.docker.com/r/hapiproject/hapi/tags?page=1&ordering=last_updated

**Comment by rcrichton** [comment]
Thanks @citizenrich, I haven't tested this at all but I'l close as all appears to be in order now.
