### ISSUE TITLE
_include=ExplanationOfBenefit:insurer not including the insurer reference in the bundle response

### ISSUE THREAD

**Issue by reshmi1990** [hapifhir/hapi-fhir-jpaserver-starter#224]
I am trying to add _include=ExplanationOfBenefit:insurer query parameter in my ExplanationOfBenefit search endpoint and even after setting the Organization resource to the insurer, it is not getting included in the bundle response. 

When I checked the ExplanationOfBenefit.java, there is no search definition or include variable defined for insurer.

Please provide a fix for the same. Or am I missing something?

Thanks
Reshmi

**Comment by jvitrifork** [comment]
@reshmi1990 have a look at ExplanationOfBenefitResourceProvider
