### ISSUE TITLE
Problem build project to generate .war file

### ISSUE THREAD

**Issue by thomaslprr** [hapifhir/hapi-fhir-jpaserver-starter#226]
Hello, 

When I want to generate the `.war` of the JPA-Server project, I get a lot of errors and the .war can't be added on the TomCat server. 

I only modified the configuration to make the JPA Server use MySql and run the deployment through Maven to get the `.war` file. 

Do you know what I should do? 

Context : 
IntelliJ IDEA - Mac OS High Sierra - TomCat9  

[Screenshot of the console](https://ibb.co/xhsZjBn)

**Comment by patrick-werner** [comment]
Hi Thomas,

This is a place for issues. For general questions please refer to:
- https://groups.google.com/g/hapi-fhir
- https://chat.fhir.org/#narrow/stream/179167-hapi

And please provide the maven build logs, and not only a screenshot of the idea hiding the underlying reasons for the failed build. Makes helping you much easier.
