### ISSUE TITLE
Docker image broken

### ISSUE THREAD

**Issue by litlfred** [hapifhir/hapi-fhir-jpaserver-starter#237]
Commit https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/44e6c65d08cdd3df7d99dbc4a02ecc858596abca breaks docker deployment.  

I ran a yaml lint against applicaiton.yaml and there is an issue around fhir_version  on line 37

When deploying, I get 

> 
> 2021-05-20 14:52:45.155 [main] ERROR o.s.boot.SpringApplication [SpringApplication.java:858] Application run failed
> java.lang.IllegalStateException: Attempted to load Config resource 'class path resource [application.yaml]' via location 'optional:classpath:/' but snakeyaml was not found on the classpath
> 	at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:47)
> 	at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:48)
> 	at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:34)
> 	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:103)
> 	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:118)
> 	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:82)
> 	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:121)
> 	at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
> 	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:230)
> 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:97)
> 	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
> 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
> 	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
> 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
> 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
> 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
> 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
> 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
> 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:173)
> 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:153)
> 	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:95)
> 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5128)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
> 	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
> 	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
> 	at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
> 	at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
> 	at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
> 	at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
> 	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
> 	at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
> 	at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
> 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
> 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
> 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
> 20-May-2021 14:52:45.166 SEVERE [main] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
> 	java.lang.IllegalStateException: Error starting child
> 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:720)
> 		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
> 		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:706)
> 		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
> 		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1848)
> 		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
> 		at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
> 		at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
> 		at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
> 		at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
> 		at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
> 		at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
> 		at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
> 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
> 		at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:843)
> 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
> 		at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
> 		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 		at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 		at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
> 		at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
> 		at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
> 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 		at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
> 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 		at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
> 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 		at org.apache.catalina.startup.Catalina.start(Catalina.java:772)
> 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 		at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
> 		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
> 	Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
> 		at org.apache.catalina.util.LifecycleBase.handleSubClassException(LifecycleBase.java:440)
> 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:198)
> 		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
> 		... 37 more
> 	Caused by: java.lang.IllegalStateException: Attempted to load Config resource 'class path resource [application.yaml]' via location 'optional:classpath:/' but snakeyaml was not found on the classpath
> 		at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:47)
> 		at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:48)
> 		at org.springframework.boot.context.config.StandardConfigDataLoader.load(StandardConfigDataLoader.java:34)
> 		at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:103)
> 		at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:118)
> 		at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:82)
> 		at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:121)
> 		at org.springframework.boot.context.config.ConfigDataEnvironment.processInitial(ConfigDataEnvironment.java:242)
> 		at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:230)
> 		at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:97)
> 		at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:89)
> 		at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:100)
> 		at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:86)
> 		at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
> 		at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
> 		at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
> 		at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
> 		at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
> 		at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
> 		at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
> 		at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
> 		at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
> 		at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
> 		at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
> 		at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
> 		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:173)
> 		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:153)
> 		at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:95)
> 		at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:174)
> 		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5128)
> 		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 		... 38 more
> 20-May-2021 14:52:45.171 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [15,512] ms
>

**Comment by theGOTOguy** [comment]
Same issue.  This was caused when you changed the `latest` tag from the `v5.3.0` image to the `v5.4.0` image.

`docker run -p 8080:8080 hapiproject/hapi:latest` or equivalently `docker run -p 8080:8080 hapiproject/hapi:v5.4.0` reproduces this issue, but using the previous version with `docker run -p 8080:8080 hapiproject/hapi:v5.3.0` works as expected.

**Comment by ZuSe** [comment]
I just provided an MR. But be careful, there are additional issues.
