### ISSUE TITLE
error while connecting to mysql backend 

### ISSUE THREAD

**Issue by kumarusa2020** [hapifhir/hapi-fhir-jpaserver-starter#245]
Hello team, I am trying to setup hapi-fhir-jpaserver-starter project to mysql 8 backend but getting attached error and unable to make this work. I have made an attempt changing mysql to h2 default then it is working. 

I am running this as docker build using below command as per documentation. also I made sure the mysql user is privileged user
./build-docker-image.sh && docker run -p 8080:8080 hapi-fhir/hapi-fhir-jpaserver-starter:latest

I have attached, console log, pom.xml & application.yaml that I am using. please help resolve this issue. 

[application.yaml.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/6563100/application.yaml.txt)
[consolelog.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/6563101/consolelog.txt)
[pom.xml.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/6563102/pom.xml.txt)

**Comment by joofio** [comment]
maybe because of this? 
19:44:52.088 [main] WARN  c.z.hikari.util.DriverDataSource [DriverDataSource.java:68] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.

**Comment by AdrianLsk** [comment]
Hi @kumarusa2020, I had the same problem. I managed to fix using the solution from a [PR](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/243). It's because of MYSQL's case sensitivity to table names, etc.

Just add 
```
command:  
   - --lower_case_table_names=1
```
 
to the MySQL service in the docker-compose.yaml

**Comment by jkiddo** [comment]
Handled with https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/243
