### ISSUE TITLE
JPA server does not start with MDM enabled

### ISSUE THREAD

**Issue by tgorton617** [hapifhir/hapi-fhir-jpaserver-starter#246]
**Reproduction steps:**

According to the README, the JPA server can be started simply by setting `hapi.fhir.mdm_enabled=true`:

```bash
docker pull hapiproject/hapi:latest
docker run -p 8080:8080 -e hapi.fhir.mdm_enabled=true hapiproject/hapi:latest
```

**Result:**

However, this results in a startup error:

```text
The bean 'mdmRuleValidator', defined in ca.uhn.fhir.jpa.mdm.config.MdmSubmitterConfig, could not be registered. A bean with that name has already been defined in ca.uhn.fhir.jpa.mdm.config.MdmConsumerConfig and overriding is disabled
```

and further down in the output:

```text
org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'mdmRuleValidator' defined in ca.uhn.fhir.jpa.mdm.config.MdmSubmitterConfig: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=ca.uhn.fhir.jpa.mdm.config.MdmSubmitterConfig; factoryMethodName=mdmRuleValidator; initMethodName=null; destroyMethodName=(inferred); defined in ca.uhn.fhir.jpa.mdm.config.MdmSubmitterConfig] for bean 'mdmRuleValidator': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=ca.uhn.fhir.jpa.mdm.config.MdmConsumerConfig; factoryMethodName=mdmRuleValidator; initMethodName=null; destroyMethodName=(inferred); defined in ca.uhn.fhir.jpa.mdm.config.MdmConsumerConfig] bound.
```

(the README also references enabling subscriptions, however the effect is the same if I add `-e hapi.fhir.subscription.resthook_enabled=true -e hapi.fhir.subscription.websocket_enabled=true` and the error appears to be a bean initialization error for the mdm code itself.)

**Expected behavior:**

It's not obvious to me whether this is a bug in the README (an undocumented configuration requirement) or the code itself, but I expected that the server would simply start with MDM enabled when using the commands above.

**Comment by afaqch115** [comment]
Hello
I have been facing the same issue while enabling the MDM configurations in application.yaml  file.
Can someone please guide me how to resolve this issue? Am i missing out some dependencies.

ERROR DETAILS:

**Result :** 

_Invalid_ bean definition with name 'mdmRuleValidator' defined in ca.uhn.fhir.jpa.mdm.config.MdmSubmitterConfig: Cannot register bean definition [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=ca.uhn.fhir.jpa.mdm.config.MdmSubmitterConfig; factoryMethodName=mdmRuleValidator; initMethodName=null; destroyMethodName=(inferred); defined in ca.uhn.fhir.jpa.mdm.config.MdmSubmitterConfig] for bean 'mdmRuleValidator': There is already [Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=ca.uhn.fhir.jpa.mdm.config.MdmConsumerConfig; factoryMethodName=mdmRuleValidator; initMethodName=null; destroyMethodName=(inferred); defined in ca.uhn.fhir.jpa.mdm.config.MdmConsumerConfig] bound.




_

**Comment by jkiddo** [comment]
I'll have a look next week

**Comment by jkiddo** [comment]
@jamesagnew you need to provide some guidance here. From the core project the construction of the bean is defined both here https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/config/MdmConsumerConfig.java#L164 and here https://github.com/hapifhir/hapi-fhir/blob/master/hapi-fhir-jpaserver-mdm/src/main/java/ca/uhn/fhir/jpa/mdm/config/MdmSubmitterConfig.java#L53

Which of the configs should be taken into account when bootstrapping it in the starter project? I'm going to make an ugly fix by enabling bean overriding capabilties until you can provide me with some guidance. The fix is in https://github.com/hapifhir/hapi-fhir-jpaserver-starter/tree/bugfix/mdm-fix

**Comment by jkiddo** [comment]
FYI @patrick-werner 👆

**Comment by jkiddo** [comment]
Fixed with https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/255
