### ISSUE TITLE
Mysql documentation update

### ISSUE THREAD

**Issue by hanneslehemets** [hapifhir/hapi-fhir-jpaserver-starter#25]
The mysql documentation states to use MySQL5Dialect
 but for default mysql it will create tables as MyIsam, not InnoDB. If MyIsam tables, then indexes larger than 1000 bytes cannot be created. Gives mysql error 1071

Proposal to change the documentation to:
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

**Comment by seanmcilvenna** [comment]
I have applied an update to README to address this. Thanks!
Commit https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/23ad3ec62cd7e493624bbcabaf04f18b02d87bf1
