### ISSUE TITLE
litle error on README.md

### ISSUE THREAD

**Issue by sekaijin** [hapifhir/hapi-fhir-jpaserver-starter#259]
In README.md file old references to the github repository remain
https://github.com/jamesagnew/***

just change https://github.com/jamesagnew/ by https://github.com/hapifhir
`
# HAPI-FHIR Starter Project
...
implement HAPI FHIR, it is not the source of the library itself). If you are looking for the main HAPI FHIR project, see here: https://github.com/jamesagnew/hapi-fhir

Need Help? Please see: https://github.com/jamesagnew/hapi-fhir/wiki/Getting-Help
`
`
# HAPI-FHIR Starter Project
...
implement HAPI FHIR, it is not the source of the library itself). If you are looking for the main HAPI FHIR project, see here: https://github.com/hapifhir/hapi-fhir

Need Help? Please see: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help
`

PS:
It's not that I don't like seeing your name ;)

**Comment by jkiddo** [comment]
fixed with https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/e0c125808339f6346ce4173d5c7f272b781ad886
