### ISSUE TITLE
Issue on actions

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/hapi-fhir-jpaserver-starter#268]
@jamesagnew / @KevinDougan-SmileCDR - can one of you guys provide the username and password in the settings of the repo so that @chgl 's pipeline can carry on with the publishing: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/runs/3443833076?check_suite_focus=true

**Comment by jvitrifork** [comment]
@tadgh - can you help us out? We can't publish new docker images until someone with admin rights 'fills out the blanks'

**Comment by tadgh** [comment]
Hey Sorry I completely missed this.  How exactly can I help here? I'm not familiar with the purpose of this PR. I may have admin access, but I don't know who owns the hapiproject dockerhub. If somebody wants to detail exactly what they need from me, happy to help.

**Comment by jkiddo** [comment]
The owner of the hapiproject looks like it's Smile CDR:
![image](https://user-images.githubusercontent.com/211696/132941241-6e336194-63e3-408a-9f3e-b861a4ca457d.png)

-maybe @seanmcilvenna knows more about the ownership part.

**Comment by jvitrifork** [comment]
Ping @seanmcilvenna

**Comment by seanmcilvenna** [comment]
I could tell it to authenticate with my Docker credentials, which have admin access to the DockerHub project... but, I don't have admin permissions to the Github project, so I can't modify the run. Not sure how I can resolve this issue.

**Comment by jkiddo** [comment]
@tadgh 👆

**Comment by chgl** [comment]
If credentials for Docker Hub were set in this repo as `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN`, then creating a new tag called `image/v5.5.0` should trigger the GitHub Action and push a new image tagged as `v5.5.0` to Docker Hub. My slight worry is that action also tries logging into the GitHub Container registry and push the image as `ghcr.io/hapifhir/hapi``, for which no credentials may be set yet.

**Comment by jkiddo** [comment]
@tadgh ping

**Comment by tadgh** [comment]
Heya, I have enabled github pages for this repo, and pushed the `gh-pages` branch. The next step is we need credentials for the dockerhub repo (I'm in the process of finding out who owns them) as secret variables in the CI settings? I'm not familiar with GH actions so I'm happy to take some guidance here

**Comment by jkiddo** [comment]
I think @seanmcilvenna owns it

**Comment by tadgh** [comment]
I've gotten admin access to both this repo, and the dockerhub page. I've added my personal access token from dockerhub and my account name as `DOCKERHUB_TOKEN` and DOCKERHUB_USERNAME` respectively. Anything else I can do?

**Comment by jkiddo** [comment]
This time the login fails at the next step: the Github Container registry

**Comment by chgl** [comment]
I think we can remove it temporarily to avoid it blocking the release. There have been updates to ghcr.io that simplify authentication and don't require the need for a Personal Access Token. I can create a PR to disable it if desired.

**Comment by jkiddo** [comment]
@chgl throw a PR and Ill add it

**Comment by jkiddo** [comment]
![image](https://user-images.githubusercontent.com/211696/134972144-61db475a-fa26-4d9f-9104-ccca2876bcf5.png)

**Comment by jkiddo** [comment]
![image](https://user-images.githubusercontent.com/211696/134972247-ed26c010-4fdd-4c8e-abfd-47eecb7c5af3.png)

**Comment by tadgh** [comment]
Glorious! We all set here then?

**Comment by chgl** [comment]
I guess we could make double-sure everything worked by updating to 5.5.**1** now 😅

**Comment by jkiddo** [comment]
@chgl if you add the arm64 stuff Im game 😉

**Comment by chgl** [comment]
Haha, sure why not. I wanted to update to the newer https://github.com/docker/metadata-action anyway.
