### ISSUE TITLE
R4 Tester UI Doesn't Count Resources Correctly

### ISSUE THREAD

**Issue by jeffeastman** [hapifhir/hapi-fhir-jpaserver-starter#27]
When I provision an STU3 server the resource counts are correct. For an R4 server they aren't even close.

<img width="1207" alt="Screen Shot 2019-05-23 at 2 57 38 PM" src="https://user-images.githubusercontent.com/8631956/58279173-b600f700-7d6b-11e9-9ac0-3f7546ecd54d.png">
<img width="1207" alt="Screen Shot 2019-05-23 at 2 58 32 PM" src="https://user-images.githubusercontent.com/8631956/58279176-b8635100-7d6b-11e9-9a75-c18a92b4d829.png">

**Comment by jamesagnew** [comment]
@jeffeastman the counts are cached so they aren't always instantly updated. Any chance that's it? Does restarting the server have any effect?

**Comment by jeffeastman** [comment]
I've noticed that delay on STU3 servers in the past. This R4 server didn't ever seem to update. I'll check and post my results. Also trying a heterogeneous Ring with a DSTU2 EHR in it.

**Comment by jeffeastman** [comment]
It appears to be my impatience and not anything fundamental. I've been able to create a Ring with DSTU2, STU3 and R4 EHR servers in it. So closing...
