### ISSUE TITLE
Add optional (or permanent) swagger-ui page

### ISSUE THREAD

**Issue by costateixeira** [hapifhir/hapi-fhir-jpaserver-starter#270]
When deploying the server, swagger-ui does not show up. 
If this is optionally activated within the application.yaml, what would that option be?
If this is something that has to be done in the code, can you please consider it? I think it would be great to have an openAPI UI by default.
I personally prefer [ReDoc](https://github.com/Redocly/redoc) but swagger-ui is fine too - i.e. possibly a (later) option to select ReDoc ? :)

**Comment by jkiddo** [comment]
@costateixeira added with https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/ea3f10ec86774abfaedf220f46a7b515f9751d26
