### ISSUE TITLE
Spring Tool Suite and eclipse gives errors

### ISSUE THREAD

**Issue by AhsanSpica** [hapifhir/hapi-fhir-jpaserver-starter#273]
Spring Tool Suite and eclipse gives errors!
Please kindly provide guidance how to run it in Eclipse and Spring Tool Suite!
What to add in pom to make it run !

![image](https://user-images.githubusercontent.com/77918674/132932961-42504adc-2c9a-44e2-bdc2-46ee2f046e77.png)

**Comment by jkiddo** [comment]
Closed due to inactivity
