### ISSUE TITLE
Docker arm64 image

### ISSUE THREAD

**Issue by kermit-sad-frog** [hapifhir/hapi-fhir-jpaserver-starter#276]
Hi all, I am a happy user of the Apple M1 chip.

I would like to use the Hapifire docker image but I am faced with an issue that it does not work for me. But I was managed to build by my own image for arm64. 

It works without any issue and as I suspect no additional effort for required from the dev side.

Could I ask you to build a docker image for the HapiFire server and push it to the docker hub?  This will save me and other developers from build locally image every time when new version arises. (also would be nice to have the arm64 image for smileCDR)

**Comment by jvitrifork** [comment]
Sure - that sounds like a good idea. Did you have to change anything or was it sufficient for you just to build it locally. AFAIK, we can add another GH action like https://medium.com/swlh/using-github-actions-to-build-arm-based-docker-images-413a8d498ee and run that as well for `arm` targets. This only highlights the need for giving the https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/268 some ❤️ (@tadgh )

**Comment by kermit-sad-frog** [comment]
I have changed nothing. I built a docker image  
``` 
docker build -t hapi-fhir/hapi-fhir-jpaserver-starter . 
``` 
and everything work as expected.

**Comment by chgl** [comment]
The docker/build-push action has a platform setting (see e.g. https://github.com/chgl/fhir-server-exporter/blob/master/.github/workflows/ci.yaml#L120 ) which allows building multiple architecturs. Both distroless and tomcat have arm V8 variants available, so adding it to the ci shouldn't be too difficult.

**Comment by chgl** [comment]
@kermit-sad-frog do you mind trying if the image built via #279 (see https://github.com/chgl/hapi-fhir-jpaserver-starter/actions/runs/1284340067) works on your hardware?

```sh
docker run --rm -it -p 8080:8080 ghcr.io/chgl/hapi:5.5.1-rc.3
```
