### ISSUE TITLE
Default to Spring Boot behaviour

### ISSUE THREAD

**Issue by jvitrifork** [hapifhir/hapi-fhir-jpaserver-starter#280]
As discussed on https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/274 - it might be worth to default to regular Spring Boot behaviour in our Docker images. The project should still support that a regular WAR file can be built - but there is little reason for this to be the default choice in the Docker file which instead should default to using Spring Boot. The assumption here is that the users that need a WAR file is not the same people that uses Docker.

As far as I can see it only expands the configuration options defaulting to the use of the self-contained Spring Boot app within the container. @tadgh / @jamesagnew / @seanmcilvenna / @chgl  let me hear what you guys think?

(the functionality of running solely as Spring Boot in the container is obtained by removing the bottom 5 lines from the Dockerfile - thats it)

**Comment by chgl** [comment]
Sounds good to me! Another possible enhancement would also be leveraging jar layering: https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#packaging.layers and https://spring.io/guides/topicals/spring-boot-docker/ (see "Spring Boot Layer Index"). 

The distroless "flavor" of the container image should already be using an embedded tomcat.

**Comment by ZuSe** [comment]
Agree.
There is also distroless with java 17 close by. Shall we upgrade to it? It tried it out for some weeks, the whole project seems to work with it.
Only think I had to do was updating maven to 3.8.3

**Comment by jkiddo** [comment]
@ZuSe will you draft a PR?

**Comment by jkiddo** [comment]
@ZuSe will you still draft the PR?

**Comment by jkiddo** [comment]
Default spring behavior can now be used with the distroless images. Fixed with https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/319
