### ISSUE TITLE
How To Enable Open API / Swagger UI 

### ISSUE THREAD

**Issue by darmawan01** [hapifhir/hapi-fhir-jpaserver-starter#285]
Hi there, i got stuck on enabling the swagger UI. i have run using docker, i can access metadata but not found with swagger-ui.

thanks for help 🙏🏻

**Comment by jkiddo** [comment]
Its comming in the next release

**Comment by darmawan01** [comment]
Got it, wait for it

**Comment by jkiddo** [comment]
Done - see https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/ea3f10ec86774abfaedf220f46a7b515f9751d26
