### ISSUE TITLE
_content search does not work with subject key

### ISSUE THREAD

**Issue by swapnilthale13** [hapifhir/hapi-fhir-jpaserver-starter#289]
Hello Team,
we have noticed that, when we do a _content search with large data set, server does not give any result. 
For example when we want do a content search for specific patient with below URL params, it does not work and gives timeout error or sometime it gives below error 
Sample url - **https://hapi.fhir.serverurl/fhir/MedicationStatement?subject=8f5b07c9-075a-4cc5-9d70-f2a272d6c64b&_content=Calcium** 
**{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Can not call next() right now, no data remains</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [ {
    "severity": "error",
    "code": "processing",
    "diagnostics": "Can not call next() right now, no data remains"
  } ]
}**

We are able to get patient specific data but when we want to do a content search by '_content' value, it does not work in conjunction with subject.
Is there any specific reason?

 **Note - Our FHIR dataset is huge around 25 to 30 million records per resource.**

**Comment by jkiddo** [comment]
That would probably be something you should address at https://github.com/hapifhir/hapi-fhir
