### ISSUE TITLE
[Update] Push master to work with HAPI 5.6.0

### ISSUE THREAD

**Issue by ZuSe** [hapifhir/hapi-fhir-jpaserver-starter#290]
New version of hapi has been released. 
We should upgrade the master to make use of it.

@jamesagnew  @tadgh  who is mainly responsible to keep the projects aligned?

**Comment by jkiddo** [comment]
Here you are @ZuSe : https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/291

**Comment by jkiddo** [comment]
- more specifically, https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/a58ef1cc7a4a572c7e1abb40d31277a581bfb877

**Comment by ZuSe** [comment]
Thanks
