### ISSUE TITLE
Add setting to enable storing of resource json in lucene index

### ISSUE THREAD

**Issue by jaison-b** [hapifhir/hapi-fhir-jpaserver-starter#298]
Add configuration setting to enable storing of resource json along with index mapping in Lucene/Elasticsearch.

This is useful in cases where after performing a search operation the resulting resource identifiers don't have to be 
looked up in the persistent storage, but rather the inline stored resource can be used instead.

For e.g - Storing Observation resource in lucene index would be useful when performing lastn operation and returning the observation resources.

**Comment by jaison-b** [comment]
This is related to https://github.com/hapifhir/hapi-fhir/issues/2838

**Comment by jkiddo** [comment]
@jaison-b it looks like this is part of https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/299, right?

**Comment by jaison-b** [comment]
Yes, it is part of #299

**Comment by jkiddo** [comment]
Then it is already added ;)
