### ISSUE TITLE
pom.xml still refers to hapi fhir 3.7 after 3.8 release

### ISSUE THREAD

**Issue by joshm-zen** [hapifhir/hapi-fhir-jpaserver-starter#30]
HAPI FHIR 3.8 has been officially released, but this project still shows as based on HAPI FHIR 3.7 (according to the pom.xml). Should it be tagged with 3.8? Is it safe to run against 3.8?

**Comment by jamesagnew** [comment]
Thanks for reporting! This is now fixed. :)
