### ISSUE TITLE
turning off snapshot generation 

### ISSUE THREAD

**Issue by AdrianLsk** [hapifhir/hapi-fhir-jpaserver-starter#303]
Hi, I am trying to import npm ig pack for nictiz.fhir.nl.stu3.zib2017 2.1.8, but it fails on snapshot generation for gp-DiagnosticResult.

Is it possible to turn it off or exclude the problematic profile using application.yaml configuration?

**Comment by jkiddo** [comment]
That would be a 'no' to both questions

**Comment by AdrianLsk** [comment]
OK, thank you

**Comment by AdrianLsk** [comment]
OK, thank you
