### ISSUE TITLE
Dealing with FHIR extensions

### ISSUE THREAD

**Issue by tsun424** [hapifhir/hapi-fhir-jpaserver-starter#306]
The chapter [3.3 Profiles and Extensions](https://hapifhir.io/hapi-fhir/docs/model/profiles_and_extensions.html) in the HAPI-FHIR website talking about supporting extensions in HAPI FHIR, but I couldn't figure out how we can support extensions in this starter project, I would appreciate if anyone could give me some advice about supporting extensions in this starter project.

**Comment by psavva** [comment]
> The chapter [3.3 Profiles and Extensions](https://hapifhir.io/hapi-fhir/docs/model/profiles_and_extensions.html) in the HAPI-FHIR website talking about supporting extensions in HAPI FHIR, but I couldn't figure out how we can support extensions in this starter project, I would appreciate if anyone could give me some advice about supporting extensions in this starter project.

What have you tried? What error are you facing?
I would imagine that you'd make more use of extensions using their fhir client, rather than something specific in the jpa server...

@jkiddo correct me if I'm wrong

**Comment by jkiddo** [comment]
@tsun424 I think your question is better suited for http://chat.fhir.org. Extensions are done when profiling. How to profile is definitely a question better suited for http://chat.fhir.org

**Comment by tsun424** [comment]
Hi @psavva , thanks for your reply, I've asked the question in the Google Group and some one replied me there, it's discussed there.

Hi @jkiddo The initial idea was information missing in the documentation, I didn't know how to report and who is maintaining the documentation, so created this issue, I'll close this issue here. Thanks.
