### ISSUE TITLE
Any plans to update to 3.8.0?

### ISSUE THREAD

**Issue by JShamdasani** [hapifhir/hapi-fhir-jpaserver-starter#31]
Hi, 3.8.0 of hapi-fhir is out now. We are basing our FHIR server off your version. Do you have any plans to upgrade? Thanks.

**Comment by jamesagnew** [comment]
Just fixed this in #30 , oddly enough.

**Comment by JShamdasani** [comment]
OK let me try and get back to.

**Comment by JShamdasani** [comment]
Looks like it works thanks! :)
