### ISSUE TITLE
No tagging for versions

### ISSUE THREAD

**Issue by joshm-zen** [hapifhir/hapi-fhir-jpaserver-starter#32]
I am using the open source HAPI FHIR server by way of deploying the jpaserver-starter and I'm trying to keep up with the releases. Normally I’d expect to see tags for this, but I don't see those for this project. Aside from inspecting the pom.xml, what indicator or marker is used to designate new releases of the hapi-fhir-jpaserver-starter project?

**Comment by seanmcilvenna** [comment]
Generally speaking, I don't believe jpaserver-starter has very many version-worthy changes. jpaserver-starter has a dependency on the hapi-fhir module which is tightly version-controlled and version-aware. It's the hapi-fhir project that really has the most of the logic, and the jpaserver-starter project is only _intended_ to be an example of how to utilize the hapi-fhir base module. However, even I use the jpaserver-starter in several different environments, and can see value in having it be based on a more formal release/version strategy.

I would probably suggest to @jamesagnew that whenever hapi-fhir has a new release, that we update pom.xml to reference the new release, and tag hapi-fhir-jpaserver-starter as a new version, matching the underlying hapi-fhir module version that's referenced in pom.xml.

**Comment by joshm-zen** [comment]
@seanmcilvenna that idea is perfect. You articulated it much better than I did/could.

**Comment by seanmcilvenna** [comment]
@jamesagnew can you comment here? I'd like to know your thoughts on versioning this project; see my above comments...

**Comment by patrick-werner** [comment]
@seanmcilvenna +1 for syncing jpa starter version with hapi-fhir version.

**Comment by seanmcilvenna** [comment]
Agreed. I'm not really privy to when updates to hapi-fhir are being released, though. So, really it would be up to @jamesagnew to ensure that the processes/procedures are in place to increment the version of hapi-fhir-jpaserver-starter along with hapi-fhir....

**Comment by jamesagnew** [comment]
FYI- I've taken the suggestions here as a part of the release process for 4.0.0. The version is synced, and I've tagged a release in this project.
