### ISSUE TITLE
How to add AuthorizationInterceptor?

### ISSUE THREAD

**Issue by longnguyen2306** [hapifhir/hapi-fhir-jpaserver-starter#33]
Hi, I am trying to add the AuthorizationInterceptor from http://hapifhir.io/apidocs-server/ca/uhn/fhir/rest/server/interceptor/auth/AuthorizationInterceptor.html
to the project. I tried to register the bean inside ApplicationContext but it doesn't seem to work.

**Comment by longnguyen2306** [comment]
Got it. For people after me, just add following line into JpaRestfulServer:


        this.registerInterceptor(new AuthorizationInceptorImpl());

**Comment by jamesagnew** [comment]
woohoo! :)
