### ISSUE TITLE
Feature: health check endpoint

### ISSUE THREAD

**Issue by XcrigX** [hapifhir/hapi-fhir-jpaserver-starter#330]
Is there a health check endpoint enabled? 

Kubernetes (and various monitoring tools) can utilize health checks endpoints to monitor the status of a server. 
I was thinking to either add SpringBoot Actuator or manually add a lightweight /health endpoint if something doesn't already exist. 
Ideally it would just return HTTP: 200 - perhaps a simple JSON return. 

SpringBoot Actuator returns something like this when enabled at the /actuator/health endpoint:
{"status":"UP","groups":["liveness","readiness"]}

Thoughts?

**Comment by jkiddo** [comment]
@XcrigX a PR using Spring Booy Actuator would be most welcome

**Comment by jkiddo** [comment]
@XcrigX added with https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/337 using vanilla Actuator setup

**Comment by XcrigX** [comment]
@jkiddo - You beat me to it by half a day. I didn't check my email this morning to see this update and spent the last hour finding the same version problem with HikariCP that you did, lol. Oh well, thanks!
