### ISSUE TITLE
Support for FHIR versions DSTU2_HL7ORG & DSTU2_1

### ISSUE THREAD

**Issue by jamesnetherton** [hapifhir/hapi-fhir-jpaserver-starter#335]
Not sure if I've missed something, but I don't see any support for using FHIR versions `DSTU2_HL7ORG` or `DSTU2_1`.

I tried running the `hapiproject/hapi` docker container with those versions and the Spring Boot app does not start.

**Comment by jamesagnew** [comment]
Got it. Well, I guess I'd say that we would certainly consider a pull request adding these, but it's unlikely that the HAPI FHIR core team would take this on, as we just haven't seen any demand.
