### ISSUE TITLE
default properties in classpath application.yaml

### ISSUE THREAD

**Issue by XcrigX** [hapifhir/hapi-fhir-jpaserver-starter#339]
I have noticed that mdm is being enabled in my deployment.  I have that property commented out in the application.yaml I'm deploying with the .jar file, but it is uncommented and 'true' in the classpath src/main/resources/application.yaml so it is not being overridden to turn off again.  
It appears advanced_lucene_indexing is also defaulted to true (not certain the implications of this one). 

I'm not familiar enough with all the properties to properly determine which are reasonable to to enable by default and require an override to disable - vs - which should be disabled by default and require an override to turn on. But I assume MDM falls into the latter category.

**Comment by XcrigX** [comment]
Hi. I'm deploying as a SpringBoot runnable .jar file. So I deploy an application.yaml file with my config into the same directory as the .jar. (I think this would be the same issue using the default Docker deployment and injecting an application.yaml into the container.)

I believe the way SpringBoot properties overrides work is that any properties set in a deployed application.yaml file will override the properties defined in the classpath (compiled) application.yaml file in src/main/resources. 
But if the deployed application.yaml file does not contain a property that is present in the compiled src/main/resources/application.yaml, it won't be overridden. 

What I think may be a problem is that many people might have an application.yaml they have taken from an earlier release and customized for their deployment.  If they then re-pull the latest updates and re-compile, and deploy an updated .jar with an existing application.yaml, any new properties turned on by default in the classpath copy of the application.yaml will turn on in their deployments.  

This happened to me with the mdm features. In an older version of the project the mdm features were commented out in the application.yaml. I carried that over into the application.yaml I am deployed. When I re-compiled the jar from master and re-deployed, it turned on since I didn't explicitly override the mdm property to turn it back off. 
Hope that makes sense. 

All that to say, what I think a solution could be is to ensure that the application.yaml in /src/main/resources has 'reasonable' defaults for all the properties. 

I would submit a PR to do this, but I don't know what every property does - so someone else may be more fit to go through it and make those determinations.   For sure it seems like MDM should not be turned on by default. I don't know about other properties.

**Comment by XcrigX** [comment]
Side note: If you run the unit/integration tests on master currently, there are several failures. If you comment out the mdm_enabled property in application.yaml they pass again. I haven't investigate the details. 

Running the tests with: 
_mvn clean verify  -Pboot_

This is the error summary:
_ERROR] Errors:
[ERROR]   ExampleServerDstu2IT.testCreateAndRead » IllegalState Failed to load Applicati...
[ERROR]   ExampleServerR4IT.testCreateAndRead:73 » ConditionTimeout Condition with ca.uh...
[ERROR]   ExampleServerR5IT.testCreateAndRead » IllegalState Failed to load ApplicationC...
[ERROR]   ExampleServerR5IT.testWebsocketSubscription » IllegalState Failed to load Appl...
[ERROR]   MultitenantServerR4IT.testCreateAndReadInTenantA » IllegalState Failed to load...
[ERROR]   MultitenantServerR4IT.testCreateAndReadInTenantB » IllegalState Failed to load...
[INFO]
[ERROR] Tests run: 11, Failures: 0, Errors: 6, Skipped: 0
[INFO]_

**Comment by jkiddo** [comment]
Fixed: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/345

**Comment by jkiddo** [comment]
and https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/bf51c2263af48f1a5927363d45c136068c78bd21
