### ISSUE TITLE
how to remain the 'id' before creating a new instance?

### ISSUE THREAD

**Issue by jimbung** [hapifhir/hapi-fhir-jpaserver-starter#356]
hi, what i want is, after creating a new instance with 'id' pre-defined in json, e.g.,
{
  "resourceType": "Organization",
  "id": "org001",
   ...
}
i want the 'id' in response data still remains 'org001', for now, it was modified with a sequence number like this:
{
  "resourceType": "Organization",
  "id": "118",
   ...
}

**Comment by kiwisky** [comment]
I have the same question...

**Comment by KevinDougan-SmileCDR** [comment]
You have to do a PUT (i.e. UPDATE) against the Resource and ID if you want to provide your own ID value:
PUT http://<SERVER_BASE_URL>/Organization/org001
{
"resourceType": "Organization",
"id": "org001",
...
}

If you do a POST (i.e. CREATE) then it won't accept your ID value and will generate a new one.
