### ISSUE TITLE
"mvn install" is failed due to running ElasticsearchLastNR4IT test error

### ISSUE THREAD

**Issue by kiwisky** [hapifhir/hapi-fhir-jpaserver-starter#357]

**Comment by kiwisky** [comment]
I got following error when I am running "mvn install"
[INFO] Running ca.uhn.fhir.jpa.starter.ElasticsearchLastNR4IT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.045 s <<< FAILURE! - in ca.uhn.fhir.jpa.starter.ElasticsearchLastNR4IT
[ERROR] ca.uhn.fhir.jpa.starter.ElasticsearchLastNR4IT  Time elapsed: 7.045 s  <<< ERROR!

It seems the test requires Docker ENV, but my server has no Docker because I am going to deploy it to a Tomcat application server.
If  I run "mvn install -DskipTests", it is successful. But I think it should not require Docker ENV? Thanks!

**Comment by jkiddo** [comment]
@kiwisky  those tests actually require docker as test containers (https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/fdfa6fd711f411c58b9175223c05141cea0598fe/src/test/java/ca/uhn/fhir/jpa/starter/ElasticsearchLastNR4IT.java#L63) are used to spin up an elasticsearch instance

**Comment by michaelabuckley** [comment]
We have a test annotation in Hapi -- `@RequiresDocker` .  If you add that to this test, it will be skipped when docker isn't present.  All tests that use docker should include `@RequiresDocker`.  See the JUnit DockerRequiredCondition .
