### ISSUE TITLE
Add `:of-type` Modifier Configuration to application.yaml

### ISSUE THREAD

**Issue by ttran428** [hapifhir/hapi-fhir-jpaserver-starter#362]
The `:of-type` token modifier was added in 5.7.0 (https://github.com/hapifhir/hapi-fhir/issues/1892), but I believe it is not configurable through the `application.yaml` file in the japserver-starter (please correct me if I'm wrong and this is supported). Could we add support for configuring it in the `application.yaml` file  (which I think is done by updating the `AppProperties.java`)?

**Comment by jkiddo** [comment]
Like https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/363 ?

**Comment by ttran428** [comment]
exactly like that :D Thanks!

closing becausea done in #363
