### ISSUE TITLE
Enabling HTTPS

### ISSUE THREAD

**Issue by hurtigcodes** [hapifhir/hapi-fhir-jpaserver-starter#369]
Hi! I'm new to this project and to HAPI FHIR overall. How do I enable HTTPS? I have it deployed in Azure as an app service with 'HTTPS only' and get the following error:
> The page was loaded over https:// but a http:// URL was specified. Check that you are not attempting to load mixed content.

I've tested a couple of different configuration options in the application.yml but I can't make it work yet. Any tips for me?

**Comment by jkiddo** [comment]
@hurtigcodes if you use the Spring Boot part of this project you should be able to do eg. https://www.thomasvitale.com/https-spring-boot-ssl-certificate/#2-enable-https-in-spring-boot 

It depends on where you wan't to terminate the SSL part which is usually done ahead of hitting the FHIR server itself as @joiskash suggests - in nginx

**Comment by hurtigcodes** [comment]
OK I will setup a machine with Nginx in front of the app service then. Thanks @joiskash @jkiddo!
