### ISSUE TITLE
Error running mvn jetty:run on localhost

### ISSUE THREAD

**Issue by quintonn** [hapifhir/hapi-fhir-jpaserver-starter#37]
I've forked and cloned your repository and I'm trying to run it locally.

I tried to run **mvn jetty:run** without making any changes but got this following error:

> [ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.4.8.v20180619:run (default-cli) on project hapi-fhir-jpaserver-starter: Failure: Address already in use: bind -> [Help 1]                                                   org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.4.8.v20180619:run (default-cli) on project hapi-fhir-jpaserver-starter: Failure 

More info further down:
> Caused by: java.net.BindException: Address already in use: bind  

This led me to think it's the port (8080) which is probably used by IIS on my windows machine.

So I changed the **server_address** value in the hapi.properties file, but i keep getting the same error.
I've tried using many different port numbers but same result.

Is there anything else I can try?

**Comment by quintonn** [comment]
I added this to the run command and it's working now:
-Djetty.port=8888

I also found an article stating that I can change the pom.xml file to add the port number.

Maybe you can update the readme.md file?

This was how I ran the server:
**mvn -Djetty.port=8888 jetty:run**

More info: 
https://www.mkyong.com/maven/jetty-java-net-bindexception-address-already-in-use/
https://www.mkyong.com/maven/maven-jetty-plugin-examples/

**Comment by jamesagnew** [comment]
Would you be willing to submit a pull request with this suggestion in the
readme?

**Comment by quintonn** [comment]
Done.

Let me know if I did it wrong or something like that.



Thanks

Quintonn

**Comment by jamesagnew** [comment]
Pull request merged. Thanks!
