### ISSUE TITLE
How to access the Database with the daoRegistry to create / read / update resources in custom functions on the server?

### ISSUE THREAD

**Issue by AdityaKBhadragond14** [hapifhir/hapi-fhir-jpaserver-starter#370]
We are writing custom APIs to extend the functionality of the FHIR server. We are able to use the client 

`    IGenericClient fhirClient = ctx.newRestfulGenericClient(serverBase);`

to create, read and modify resources. But It seems wrong to use the RestfulClient when we are the same server.. Is there some documentation around using the daoRegistry? 

cc: @joiskash

**Comment by jamesagnew** [comment]
We've never really written any specific documentation on how to use the DaoRegistry (pull requests against the docs would certainly be appreciated!) but FWIW we have done this a lot internally, and I know lots of other HAPI FHIR users do this as well.
