### ISSUE TITLE
6.1.0 snap

### ISSUE THREAD

**Issue by jkiddo** [hapifhir/hapi-fhir-jpaserver-starter#374]
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/d660dc137004d8bbe2c635fe6b7ae31701f286c0/pom.xml#L17 - @tadgh we haven't made a release for the 6.0.0 part yet. Mind if I turn this back to 6.0.0, tag, release, publish, and then 'turn it back to the future' as in 6.1.0-snapshot?

**Comment by tadgh** [comment]
Hey @jkiddo , I coulda sworn we tagged the 6.0.0 release, but am currently on a bus so I can't check. If you say it is not done, it was likely forgotten. Feel free to do what you outlined here.

For what it's worth the only reason I bumped it because we realized our 6.0.0 release effectively mandates running with lucene on due to the ValueSetOperationProvider relying on a non optional IFullTextSvc

**Comment by jkiddo** [comment]
@tadgh woops - I totally missed that you tagged it.

**Comment by jkiddo** [comment]
Bugger - now the pipeline fails ... :(

**Comment by tadgh** [comment]
Link me to it? I may be able to make the required fixes and re-tag if needed.

**Comment by jkiddo** [comment]
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/actions/runs/2364287169

**Comment by jkiddo** [comment]
But if 6.0.0 requires Lucene I guess that a class shadowed local version of ValueSetOperationProvider in the starter project could do the job for now

**Comment by tadgh** [comment]
huh i never considered that option, and to be honest, I've never done that before. I can link you the "fixed" version of that class, if you want to add it. here is a version of the class (currently in PR) which fixes this issue: https://github.com/hapifhir/hapi-fhir/blob/f0feca657866fc9ac97a9cb491ce0e1e83847883/hapi-fhir-jpaserver-base/src/main/java/ca/uhn/fhir/jpa/provider/ValueSetOperationProvider.java

**Comment by jkiddo** [comment]
@tadgh I've added the shadowing on https://github.com/hapifhir/hapi-fhir-jpaserver-starter/tree/rel_6_0_1 and seems to work as intended

**Comment by jkiddo** [comment]
In the mean time, I see there's now a https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/73d7ee185771a10e9156d7b2d97fe7e5af6ae20f/pom.xml#L17 (6.0.1). Should I release the current branch with the class shadowed version or should the starter-project be bumped to 6.0.1 and then released?

**Comment by tadgh** [comment]
6.0.1 contains the fix , so you can definitely rely on that one instead of
using the shadowed class

**Comment by jkiddo** [comment]
When will 6.0.1 be released?

**Comment by tadgh** [comment]
Soon as our smoke testing is done, you can communicate with @Mark Iantorno
***@***.***>  who will be releasing it. I am heading on
vacation :)

**Comment by jkiddo** [comment]
I'll assume that would be @markiantorno ;) - and I'm also heading on vacation :)

**Comment by tadgh** [comment]
You got it that's the one. Enjoy vacation !

**Comment by markiantorno** [comment]
It's in now. Just rebuilt it and it worked.

**Comment by jkiddo** [comment]
@markiantorno which commit should be tagged?
