### ISSUE TITLE
Publish starter project to the maven central again

### ISSUE THREAD

**Issue by Eernie** [hapifhir/hapi-fhir-jpaserver-starter#375]
It would be very helpful if the project is also published to the maven central. We would like to use the hapi fhir server, but we need to extend it with some custom logic for authorization and operations. Currently we can only clone the project and backfeed changes. This is quite labor intensive. Ideally we would grab the starter project from the maven central and then extend it with our own code.

**Comment by jkiddo** [comment]
I agree - @markiantorno would you agree?

**Comment by postjohannes** [comment]
I also would see that happen

**Comment by jmeinsma** [comment]
I also agree

**Comment by Gerrit23** [comment]
That woud be great, we also like to extend on the starter project.

**Comment by Eernie** [comment]
@jkiddo / @markiantorno any updates on this?

**Comment by markiantorno** [comment]
I'll look into getting this set up.

**Comment by Eernie** [comment]
@markiantorno This is great. Any ETA on when you'll create the release pipeline?
