### ISSUE TITLE
goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0

### ISSUE THREAD

**Issue by psx1lin** [hapifhir/hapi-fhir-jpaserver-starter#379]
Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.0.0:enforce (enforce-maven) on project hapi-fhir-jpaserver-starter: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

===version
Apache Maven 3.5.4 (Red Hat 3.5.4-5)
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.15+10-LTS, mixed mode, sharing)

**Comment by jkiddo** [comment]
Closing as stale
