### ISSUE TITLE
Doesnt work with JAVA 11 on windoew

### ISSUE THREAD

**Issue by saurabh-singh-17** [hapifhir/hapi-fhir-jpaserver-starter#390]
![image](https://user-images.githubusercontent.com/12830545/176155625-5c96c70f-2259-499e-947b-b39b46f27f3a.png)

It looks for JAVA 17.

**Comment by KevinDougan-SmileCDR** [comment]
This is by design.
The Unit Tests utilize some JDK 17 features, so you need that to build & test it.
