### ISSUE TITLE
Tomcat-flavored container is not starting the server

### ISSUE THREAD

**Issue by chgl** [hapifhir/hapi-fhir-jpaserver-starter#392]
When testing https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/391 I noticed that the HAPI FHIR server wouldn't start when using the tomcat "flavored" image:

```sh
docker build -t docker.io/hapiproject/hapi:latest-tomcat --target=tomcat .
docker run --rm -it -p8080:8080 docker.io/hapiproject/hapi:latest-tomcat
```

This does start the tomcat server but HAPI itself is never deployed.

I believe the issue is in https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/Dockerfile#L31 - the .war file is copied to  `/opt/bitnami/tomcat/webapps_default` instead of `/opt/bitnami/tomcat/webapps`. Changing it to the latter correctly starts the FHIR server.

If this makes sense I'd be happy to create a PR changing the .war location.

**Comment by jkiddo** [comment]
@chgl Please do
