### ISSUE TITLE
Error: HTTP 500 : Failed to call access method: org.thymeleaf.exceptions.

### ISSUE THREAD

**Issue by jeffeastman** [hapifhir/hapi-fhir-jpaserver-starter#40]
Opening a ticket on this so it doesn't get lost in email threads:

Using the v4.0.0-SNAPSHOT of July 22 and happy-fhir-structures-r4-3.7.0.jar and posting via the UI, I get

Warning!
Error: HTTP 500 : Failed to call access method: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "not result.resource.interpretation.textElement.empty" (template: "diagnosticreport" - line 68, col 17)

When posting this bundle:

[bundle.json.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/3435946/bundle.json.txt)

**Comment by jeffeastman** [comment]
Posting this bundle via the UI using happy-fhir-structures-r4-3.8.0.jar, I get

Warning!
Error: HTTP 500 : Failed to call access method: org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "Untitled Diagnostic Report" (template: "diagnosticreport" - line 15, col 152)

[bundle2.json.txt](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/files/3436043/bundle2.json.txt)

**Comment by seanmcilvenna** [comment]
This should be an issue with [hapi-fhir](https://github.com/jamesagnew/hapi-fhir) rather than hapi-fhir-jpaserver-starter. Please submit this issue to that project, instead. Thank You
