### ISSUE TITLE
Filesystem storage for binary data possible?

### ISSUE THREAD

**Issue by emomicrowave** [hapifhir/hapi-fhir-jpaserver-starter#402]
Let me start off by saying that I know SmileCDR and this project are different products. That said, I've followed the [SmileCDR documentation](https://smilecdr.com/docs/fhir_repository/binary_data.html) for binary storage using `$biary-access-write` and `$binary-access-read`. Looking at their documentation, there are multiple config options that aren't available in the `application.yaml` of this project.  

Since I am working with large (>100MB) binary files, the option to store these files on the filesystem instead of in a DB seems particularly appealing to be. However, is it even possible in the jpa server? I skimmed the source code (did some searches) but didn't find anything.

So my questions are: Am I missing something? Is it not implemented yet? Is implementation out of scope?

Thank you in advance!

**Comment by tadgh** [comment]
Heya, yup this is definitely possible, the Filesystem mode is available in HAPI-FHIR. The two components that matter are: 
1. BinaryStorageInterceptor.
2. the interface IBinaryStorageSvc. 

To make the JPA Server use the FilesystemBinaryStorageSvcImpl, it should be sufficient to define it as a bean as such: 
```
       @Bean
	public IBinaryStorageSvc binaryStorageSvc() {
            return new FilesystemBinaryStorageSvcImpl("/path/to/base/binary/dir");
        }
```

Note how JPA Server's FhirConfigCommon class defines this bean, but instead returns a DatabaseBlobBinaryStorageSvcImpl. That is where I would start :)
