### ISSUE TITLE
Unable to perform bulk import

### ISSUE THREAD

**Issue by amuslim-fn** [hapifhir/hapi-fhir-jpaserver-starter#404]
I'm attempting to bulk import a bundle of resources to a local HAPI-FHIR instance that I have running via Docker Hub as described [here](https://hub.docker.com/r/hapiproject/hapi) but am repeatedly running into the `not-supported` error below:

`{'resourceType': 'OperationOutcome', 'text': {'status': 'generated', 'div': '<div xmlns="http://www.w3.org/1999/xhtml"><h1>Operation Outcome</h1><table border="0"><tr><td style="font-weight: bold;">ERROR</td><td>[]</td><td><pre>Invalid request: The FHIR endpoint on this server does not know how to handle POST operation[$import] with parameters [[]]</pre></td>\n\t\t\t</tr>\n\t\t</table>\n\t</div>'}, 'issue': [{'severity': 'error', 'code': 'not-supported', 'diagnostics': 'Invalid request: The FHIR endpoint on this server does not know how to handle POST operation[$import] with parameters [[]]'}]}`

This is occurring when I try to make a POST request to my local HAPI-FHIR instance at `http://localhost:8080/fhir/$import` with the headers `{'Accept-Charset': 'utf-8', 'Accept': 'application/fhir+json;q=1.0, application/json+fhir;q=0.9', 'User-Agent': 'HAPI-FHIR/6.0.0 (FHIR Client; FHIR 4.0.0/R4; apache)', 'Accept-Encoding': 'gzip', 'Content-Type': 'application/fhir+json; charset=UTF-8', 'prefer': 'respond-async'}`

Despite trying different payloads (the bundle to be imported on its own, the bundle wrapped within a Parameters resource), I'm getting the same error.

Not quite sure where I'm going wrong, could someone please help resolve this?
Thank you!

**Comment by krish-freenome** [comment]
I see that the BulkDataExportProvider is being imported [here](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java#L15), and then registered [here](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/BaseJpaRestfulServer.java#L363).  I wonder if something similar needs to be done with a BulkDataImportProvider?

However, looking in the hapi-fhir repo, I don't see a providers folder in Import [where I would expect](https://github.com/hapifhir/hapi-fhir/tree/master/hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/bulk/imprt), while [there is such a provider](https://github.com/hapifhir/hapi-fhir/tree/master/hapi-fhir-storage/src/main/java/ca/uhn/fhir/jpa/bulk/export) for Export.  Not sure where that leaves this
