### ISSUE TITLE
docker still use MySQL

### ISSUE THREAD

**Issue by realizm** [hapifhir/hapi-fhir-jpaserver-starter#412]
MySQL is deprecated on hapi-fhir v6.x.
https://hapifhir.io/hapi-fhir/docs/server_jpa/database_support.html

But jpaserver starter docker still uses MySQL.
[docer-compose.yml](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/docker-compose.yml)
`image: mysql:latest`

**Comment by jkiddo** [comment]
@realizm will you make a PR to fix this?
