### ISSUE TITLE
Deploying on centos release 8 and Tomcat 10.x

### ISSUE THREAD

**Issue by tjforbes** [hapifhir/hapi-fhir-jpaserver-starter#424]
i was able to cleanly build the WAR file (including the  tests)  with mcn clean install.  The WAR file deploy to tomcat looked ok but tossed a 404 error when trying to access.  reverting back to tomcat 8.5 seems to resolved the problem so i'm guessing  there may be inconsistencies with some of the more recent Servlet's?  I'm new to working with mvn, tomcat and of course hapifhir and would like to release it on a newer platform if possible -  on centos really paving the way towards a Redhat pilot release,  Has anyone had luck deploying on tomcat 10.x? I used Java jdk 17 and maven 3.8.3 to build the WAR.  Tomcat is running with the same java base (17) mentioned on the current 8.5 version and deployed form the same WAR  but will not run on 10.x

**Comment by jkiddo** [comment]
Is it mandatory for you to deploy to a managed tomcat instance? The other default option is to run it with the embedded tomcat

**Comment by tjforbes** [comment]
no its not mandatory in fact ver 9 works better for at this time and is preferred.  Some of the post was to discover if im doing something wrong, or if not then alert others to this condition, and finally to discover if there will be at some point some possible plan to figure out what changed.  We think this might be somewhat common as we have seen this as well with component releases for things like Oracle Rest Data Services - we've yet to solve.  That said we will deploy to a managed tomcat Instance and as i say 9 works

**Comment by KevinDougan-SmileCDR** [comment]
Closing this issue since it is working when deployed to a managed Tomcat instance.
