### ISSUE TITLE
connection to aws postgresql instance to docker-compose

### ISSUE THREAD

**Issue by kanth233** [hapifhir/hapi-fhir-jpaserver-starter#425]
i have successfully deployed hapi-fhir server in amazon-linux2 ec2 instance and using docker-compose i have created two containers which is one hapi-server-container and other postgres db container and i am able to successfully connect to db from my pg admin but i wanted to have real database instaed of virtual one like the container and wanted to connect to that real postgresdb which is deployed aws rds console and so how can i achieve to connect from real db to this docker hapi container

**Comment by jkiddo** [comment]
Closing as stale
