### ISSUE TITLE
Server requires a restart everyday

### ISSUE THREAD

**Issue by FrancisChristy** [hapifhir/hapi-fhir-jpaserver-starter#431]
I have hosted the server in ec2 using docker. The server is going down after a few hours. So, I have to manually restart the server everyday in the morning. Is there some fix for this?

**Comment by XcrigX** [comment]
I think you'll need to provide more details if you hope to get any assistance - such as the server log and details on what you are observing.

**Comment by FrancisChristy** [comment]
Actually....there are no logs. I just restart the server using "docker start". By the next day, the server would have gone down. So when i try accessing using postman, it returns an error. When i restart it, the error disappears. So, I just wanna know why the server is going down after every few hours. I'm using docker hapi fhir starter pack.

**Comment by XcrigX** [comment]
The HAPI server should be logging to console in the docker container. You can view the logs using docker commands such as: 
_docker logs <containername>_ (or something similar - check the docker documentation). You can tail the logs I think with: _docker logs -f <containername>_ - so you could keep a watch on it overnight if you can't see the logs after the container crashes. 

Lots of things could be happening,  but I assure you the server is not designed to crash after a few hours.

**Comment by jamesagnew** [comment]
Closing due to lack of response. @FrancisChristy please feel free to open a ticket if this happens again. Please make sure to include all relevant logs, environment details, etc.
