### ISSUE TITLE
Missing PHI encryption 

### ISSUE THREAD

**Issue by shubhddn01** [hapifhir/hapi-fhir-jpaserver-starter#436]
Hello Team, 
I am using this repo and found that resource data is not saved as encrypted in db. As HIPAA always recommend to save the PHI data in encrypted form.

Can you please suggest what all options are open for me to solve this issue.

**Comment by jkiddo** [comment]
@shubhddn01 supporting encryption-at-rest is a DB specific feature. Look into your preferred DB engine and check if it supports that.

**Comment by shubhddn01** [comment]
Thanks a lot man.
