### ISSUE TITLE
Improve $poll-export-status to include all required attributes.

### ISSUE THREAD

**Issue by sjayswal** [hapifhir/hapi-fhir-jpaserver-starter#437]
$export-poll-status is not currently sufficient. According to the HL7 [specification] for bulk export, the poll response for a completed Bulk Export job is required to include five elements:

{{transactionTime}}
{{request}}
{{output}}
{{requiresAccessToken}}
{{error}}

The above mentioned issues have been fixed here for different repository of hapifhir.
https://github.com/hapifhir/hapi-fhir/issues/4084
https://github.com/hapifhir/hapi-fhir/issues/4051 

We are using hapi-fhir-jpaserver-starter 5.7.0 version.  

**Can you please fix above mentioned issues for hapi-fhir-jpaserver-starter project as well or suggest if i  am missing anything.**

**Comment by jkiddo** [comment]
@sjayswal since its fixed in core, it will probably go into next release of the starter project whenever the next version of core is released.

**Comment by jamesagnew** [comment]
Yup, these fixes are currently being worked on and should be present in
6.2.0 when that's released.

Cheers,
James

**Comment by sjayswal** [comment]
@jkiddo and @jamesagnew ,

Thank you for your quick response. Good to hear that. 

**Can you please tell me when the 6.2.0 version will be released ?**

**Comment by jkiddo** [comment]
Its usually around a week after the core is released.

**Comment by sjayswal** [comment]
@jkiddo,

Okay thanks for the update. Can you please tell me when the core will be released ?

**Comment by jamesagnew** [comment]
Should be roughly the second week of November.
