### ISSUE TITLE
Description of Configuration Variables (datasource.max-active vs hikari.maximum-pool-size)

### ISSUE THREAD

**Issue by RafaelWO** [hapifhir/hapi-fhir-jpaserver-starter#438]
Hi, I'm having trouble understanding some variables from the configuration file `application.yaml`. Most of them are clear or documented in the [wiki](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/wiki/Configuration) but e.g. I don't know what the `datasource.max-active` corresponds to (compared to the `hikari.maximum-pool-size` - which is not mentioned in the wiki).

Can someone help me here? Thanks!

If there are docstrings in the main HAPI repo for those variables (pls point me towards them), I'm happy to add them to the wiki here.

P.S. It would be great if we can update the wiki afterwards :)

**Comment by KevinDougan-SmileCDR** [comment]
Hi @RafaelWO ,

These config settings are automatically mapped by the Spring Framework itself.
See more info about the Spring Datasource Configuration properties here:
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#data.sql.datasource.configuration

The Spring Boot Release Notes discusses how the `common` properties are mapped to the `spring.datasource` namespace and how driver-specific properties are separated into their own namespaces:
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.4.0-M1-Release-Notes#datasource-binding

Therefore, it is important for you to know if you are mapping a `common` property or a database driver-specific property in the `application.yaml` file.

In this case, the `max-active` property is a common one and the `maximum-pool-size` property is specific to the `hikari` driver.

**Comment by RafaelWO** [comment]
Thanks for your answer! Does this effectively mean that for configuring the max connections I can ignore the common `max-active` and just set `hikari.maximum-pool-size`?

Sorry if this is a dumb question but I have not much experience with Java Sprint (Boot).
