### ISSUE TITLE
Question regarding implementation of OpenSearch

### ISSUE THREAD

**Issue by gjergjsheldija** [hapifhir/hapi-fhir-jpaserver-starter#447]
Hi,

I've managed to have HAPI working with OpenSearch. The changes, need to happen in the `ca.uhn.fhir.jpa.search.lastn` and are a bit heavy. Basically, there is the need to refactor the `Elasticsearch*` classes in order to be able to handle both Elastic and OpenSearch.
After that, those changes need to be also enabled in the jpastarter project.
I can gladly create a PR on `hapi-fhir` project. The things I'm not sure are : 
- is anyone already working on this ?
- does it make sense to have support for both ?

thank you
Gjergj

**Comment by XcrigX** [comment]
@gjergjsheldija  - you might pose this question on the main HAPI project - I did see this prior related issue there: 
https://github.com/hapifhir/hapi-fhir/issues/3167

**Comment by gjergjsheldija** [comment]
@XcrigX  thank you, will add there

**Comment by jkiddo** [comment]
@gjergjsheldija are you good with closing it here and continuing on the core project?
