### ISSUE TITLE
HAPI FHIR is targeting JDK 11 for published binaries, but we require JDK 17 to build and test this library.

### ISSUE THREAD

**Issue by Navina107** [hapifhir/hapi-fhir-jpaserver-starter#452]
When tried to run the hapi-fhir-jpaserver-starter code , i get error stating that HAPI FHIR is targeting JDK 11 for published binaries, but we require JDK 17 to build and test this library. 

I run with hapi fhir version 6.1.0 , java 11 and maven 3.8.6 .  The documentation says minimum required version is jdk 11

**Comment by KevinDougan-SmileCDR** [comment]
We use some advanced features of Java in our Unit & Integration Tests, so that's why you need Java 17 to build the project.
However, you only need Java 11 to execute the binaries since we target that version for published binaries.
