### ISSUE TITLE
$evaluate-measure with cql_enabled isn't working in 6.2.2

### ISSUE THREAD

**Issue by lukeaduncan** [hapifhir/hapi-fhir-jpaserver-starter#464]
In the latest release (6.2.2) from docker and from this repository, the hapi.fhir.cql_enabled flag doesn't seem to be working.  

Trying with v6.1.0 works fine, but updating to :latest (v6.2.2) doesn't.  The $evaluate-measure operation isn't in the conformance statement and when trying to access it this error is returned:

Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Measure/BreastCancerScreeningFHIR/$evaluate-measure] with parameters [[]]

**Comment by KevinDougan-SmileCDR** [comment]
Hi @lukeaduncan,

Keep an eye on this `hapi-fhir` PR as it will upgrade a bunch of CQL-related libraries and improve overall capabilities immensely:

https://github.com/hapifhir/hapi-fhir/pull/4347

**Comment by CzarMich** [comment]
> In the latest release (6.2.2) from docker and from this repository, the hapi.fhir.cql_enabled flag doesn't seem to be working.
> 
> Trying with v6.1.0 works fine, but updating to :latest (v6.2.2) doesn't. The $evaluate-measure operation isn't in the conformance statement and when trying to access it this error is returned:
> 
> Invalid request: The FHIR endpoint on this server does not know how to handle GET operation[Measure/BreastCancerScreeningFHIR/$evaluate-measure] with parameters [[]]

I am having the same error. Will be happy to get something working
