### ISSUE TITLE
H2 database error in branch rel_4_0_0

### ISSUE THREAD

**Issue by sdatchley** [hapifhir/hapi-fhir-jpaserver-starter#47]
In the current rel_4_0_0 branch, you have an implicit relative path which is disabled by default in H2:

**IMPLICIT_RELATIVE_PATH
System property h2.implicitRelativePath (default: false).
If disabled, relative paths in database URLs need to be written as jdbc:h2:./test instead of jdbc:h2:test.**

The exception is: Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:file:target/jpaserver_derby_files". Use an absolute path, ~/name, ./name, or the baseDir setting instead. [90011-199])

Therefore, to run the server with H2, you need to change
datasource.url=jdbc:h2:file:target/jpaserver_derby_files
to something like
datasource.url=jdbc:h2:file:./target/database/h2

**Comment by jamesagnew** [comment]
Makes sense to me, thanks for the suggestion. Fix coming up!

**Comment by patrick-werner** [comment]
Wouldn‘t it be easier to just set h2.implicitRelativePath = true if h2 is used?

**Comment by jamesagnew** [comment]
I'm not actually clear on how that is set, but.... maybe? :)

**Comment by sdatchley** [comment]
Not sure if there are other ways of setting, but per this page, neither of those 2 options seems ideal.

[H2 SysProperties](http://www.h2database.com/javadoc/org/h2/engine/SysProperties.html?highlight=Implicit%2Crelative&search=Implicit%20relative)
