### ISSUE TITLE
Duplicate Key Error management:spring

### ISSUE THREAD

**Issue by szitello** [hapifhir/hapi-fhir-jpaserver-starter#470]
I dont see any duplicate keys.  Using unedited src/main/resources/application.yaml from this distro.

hapi-fhir-jpaserver-start    | 2022-12-21 23:45:32.286 [main] ERROR o.s.boot.SpringApplication [SpringApplication.java:824] Application run failed
hapi-fhir-jpaserver-start    | org.yaml.snakeyaml.constructor.DuplicateKeyException: while constructing a mapping
hapi-fhir-jpaserver-start    |  in 'reader', line 3, column 1:
hapi-fhir-jpaserver-start    |     management:
hapi-fhir-jpaserver-start    |     ^
hapi-fhir-jpaserver-start    | found duplicate key spring
hapi-fhir-jpaserver-start    |  in 'reader', line 16, column 1:
hapi-fhir-jpaserver-start    |     spring:
hapi-fhir-jpaserver-start    |     ^
hapi-fhir-jpaserver-start    |
hapi-fhir-jpaserver-start    |  at org.yaml.snakeyaml.constructor.SafeConstructor.processDuplicateKeys(SafeConstructor.java:123)

**Comment by KevinDougan-SmileCDR** [comment]
Hi @szitello ,

Can you please provide more details on exactly what you are doing and how you are seeing this ERROR above?

For example, I just pulled down the latest `master` branch, built it with `mvn clean install -DskipTests` and then ran it using `mvn jetty:run` and it started up just fine for me.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/72025369/209142043-d0cd1b7c-081e-4b23-9c43-34fbbc841692.png">

Thanks!
Kevin

**Comment by szitello** [comment]
1. I Downloaded the .zip file, unpacked. assume is also master.
2. I ran the build_docker_image.sh script, some Warnings but no Errors
3. docker-compose up.   This is when I receive the errors listed above

**Comment by szitello** [comment]
1. I downloaded most recent today.
The old errors went away.  

New errors:
hapi-fhir-jpaserver-start    | 2022-12-22 15:50:37.891 [main] INFO  o.h.annotations.common.Version [JavaReflectionManager.java:56] HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
hapi-fhir-jpaserver-start    | 2022-12-22 15:50:38.195 [main] INFO  com.zaxxer.hikari.HikariDataSource [HikariDataSource.java:110] HikariPool-1 - Starting...
hapi-fhir-jpaserver-start    | org.h2.message.DbException: Log file error: "/app/target/database/h2.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/app/target"" [90062-214]" [90034-214]
hapi-fhir-jpaserver-start    | org.h2.message.DbException: Log file error: "/app/target/database/h2.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/app/target"" [90062-214]" [90034-214]

I dont think the application.yaml and the docker-compose.yml are in concert though as the docker-compose uses postgres and the application.yml H2

2.  Used docker run instead.  Same errors as above.
org.h2.message.DbException: Log file error: "/app/target/database/h2.trace.db", cause: "org.h2.message.DbException: Error while creating file ""/app/target"" [90062-214]" [90034-214]
        at org.h2.message.DbException.get(DbException.java:212)
        at org.h2.message.TraceSystem.logWritingError(TraceSystem.java:294)
        at org.h2.message.TraceSystem.openWriter(TraceSystem.java:315)
        at org.h2.message.TraceSystem.writeFile(TraceSystem.java:263)
