### ISSUE TITLE
SpringBoot and Logback missing org/slf4j/impl/StaticLoggerBinder.  Need to update to SpringBoot 3.0.1.

### ISSUE THREAD

**Issue by lukedegruchy** [hapifhir/hapi-fhir-jpaserver-starter#471]
Please see: [466](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/466).

# Background

* In master, jpaserver-starter is using `hapi-fhir` 6.2.2, which uses an older version of Logback that still contains org/slf4j/impl/StaticLoggerBinder
* In order to fix [466](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/466) (as of this writing, still pending), we needed to explicitly downgrade `logback-core` and `logback-classic` to 1.2.10.   Otherwise, the application and unit tests will fail with `java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder`
* This issue is apparently fixed in Spring 3.0.1 and up:  https://github.com/spring-projects/spring-boot/issues/12649

# Fix

* The ideal solution is to upgrade to SpringBoot 3.0.1 and explicitly within the jpaserver-starter pom.xml.   This should not depend on any springboot configuration in hapi-fhir since that may be removed there entirely
* However, this is a major version jump and will likely initially result in errors and dependencies to be resolved/upgraded

**Comment by jkiddo** [comment]
@lukedegruchy we've upgraded now. Should this be closed?
