### ISSUE TITLE
Allow static content root to be configured

### ISSUE THREAD

**Issue by costateixeira** [hapifhir/hapi-fhir-jpaserver-starter#486]
The static content hosting always starts at <host>/static/...
I would like to have it possible to configure, with a property in application.yaml.

For my cases I want to have the folder /apps mapped to <host>/apps, (which perhaps means the static content path would be /?)

**Comment by jkiddo** [comment]
Fixed in https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/605
