### ISSUE TITLE
any plans to move on to spring boot 3+ and jakarta persistence?

### ISSUE THREAD

**Issue by ksanjeev9211** [hapifhir/hapi-fhir-jpaserver-starter#513]
I was trying to customize the fhir jpa server, however, could not progress much as our technical stack is spring-boot 3+ and unfortunately,  hapi-fhir-jpa-server is not yet compatible with Jakarta EE 10.

Any plans to upgrade?

**Comment by abeshenov** [comment]
Related active issue with some discussion: https://github.com/hapifhir/hapi-fhir/issues/2082

**Comment by jkiddo** [comment]
See https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/473

**Comment by jkiddo** [comment]
Will be fixed with https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/618
