### ISSUE TITLE
Add $convert operation to capabilities of server

### ISSUE THREAD

**Issue by paulolaup** [hapifhir/hapi-fhir-jpaserver-starter#516]
For the purposes of using the server within another project ([TerminoloGit](https://gitlab.com/elga-gmbh/termgit-dev)) I require the availibility of **[base]/$convert** endpoint. I don't think its implementation would require a lot of work. If you'd like, I would implement it myself and create a pull request once its ready.

To implement:
**[base]/$convert** endpoint to convert FHIR instance data between FHIR-JSON and FHIR-XML

**Comment by patrick-werner** [comment]
I like the idea, but i think this should be implemented in the hapi project here:
https://github.com/hapifhir/hapi-fhir

**Comment by paulolaup** [comment]
Thx for the info. I'll redirect my proposal to the hapi project.
