### ISSUE TITLE
apply  mdm-rules.json to docker  container

### ISSUE THREAD

**Issue by yfann** [hapifhir/hapi-fhir-jpaserver-starter#526]
Hi team,

I did some change in mdm-rules.json. How can I apply the changed mdm-rules.json to my local hapi docker instance?
Like the way config does: 
`docker run -p 8090:8080 -e "--spring.config.location=classpath:/another.application.yaml" hapiproject/hapi:latest`

**Comment by abeshenov** [comment]
`mdm-rules.json` is loaded here as a Java resource: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/4077cf58404afccd7597978fc5e19851d4ff22fe/src/main/java/ca/uhn/fhir/jpa/starter/mdm/MdmConfig.java#L29

The default image `hapiproject/hapi` will have `mdm-rules.json` packaged inside `/app/main.war`. So you should compile your own custom image with modified resources (or modified `MdmConfig` class to load `mdm-rules.json` from somewhere else).
