### ISSUE TITLE
Unable to set http context path with helm chart

### ISSUE THREAD

**Issue by gmej** [hapifhir/hapi-fhir-jpaserver-starter#547]
When installing the server with helm, it is not possible to set the http context path to work behind a reverse proxy. The workaround is building the image locally and pushing it, editing the values in application.yaml (setting server.servlet.context-path to the desired value). It would be nice to be able to edit that configuration directly in the values.yaml file.

**Comment by chgl** [comment]
This should work by setting an env var as well, i.e. via the `extraEnv` value. SERVER_SERVLET_CONTEXT_PATH should work (untested).

**Comment by gmej** [comment]
I tried this and it is working. I can confirm that `SERVER_SERVLET_CONTEXT_PATH` works under `extraEnv`. This should be better documented.

The use of extraEnv is documented, but I think documentation should include a more explicit reference that it is possible to set all variables in `application.yaml` under `extraEnv`, maybe with an example.
