### ISSUE TITLE
When the data source is changed to MS SQLSERVRE, the execution of chain queries_ Sort error

### ISSUE THREAD

**Issue by YangZeLin3576** [hapifhir/hapi-fhir-jpaserver-starter#551]
step1: Change the data source to MS SQLSERVRE
![image](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/105766203/927f014d-e59b-4a00-a0c9-1f242675d871)

step 2: According to the document, delete the configuration
![image](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/105766203/50b8ac6f-843c-46eb-ab07-250acc6bb061)

step 3: Start the fhir service using the 'mvn - Djetty. port=8080 jetty: run command

step 4: Add a set of basic data for testing, including ServiceRequest resources and Patient resources
![image](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/105766203/daa3ffcc-1a71-4c8d-bc2d-b721e5a4476a)

step 5: Use this URL to execute a query: http://localhost:8080/fhir/ServiceRequest?_sort=Patient:subject.name
![image](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/105766203/8a3db531-7c07-4c71-a6d2-a2473da89909)

Now can see that there is an exception in the above figure, which should be translated as: the operand data type 'varchar' is invalid for the 'minus' operator.

**Comment by jkiddo** [comment]
Which database are you using?

**Comment by XcrigX** [comment]
I just tried this query on my HAPI server (hitting an Azure SQL database), I receive this error, FWIW: 

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "code": "processing",
            "diagnostics": "HAPI-1194: Unknown _sort parameter value \"Patient:subject.name\" for resource type \"ServiceRequest\" (Note: sort parameters values must use a valid Search Parameter). Valid values for this search are: [_content, _id, _lastUpdated, _profile, _security, _source, _tag, _text, authored, based-on, body-site, category, code, encounter, identifier, instantiates-canonical, instantiates-uri, intent, occurrence, patient, performer, performer-type, priority, replaces, requester, requisition, specimen, status"
        }
    ]
}
```

**Comment by jkiddo** [comment]
If it is a dialect issue then we need someone from the core team to be aware of it

**Comment by XcrigX** [comment]
I use this dialect with AzureSQL:
`hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect`

**Comment by XcrigX** [comment]
I added that PR, but the original PR didn't have the language about removing the dialect: 
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/347/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R218

Anyway, as mentioned, I set a dialect when connecting to SQL Server so try and let us know.

**Comment by XcrigX** [comment]
I think @jkiddo's instincts are correct and this smells potentially like a dialect issue. Did you try adding one?

**Comment by jalbertoa** [comment]
> I added that PR, but the original PR didn't have the language about removing the dialect: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/347/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R218
> 
> Anyway, as mentioned, I set a dialect when connecting to SQL Server so try and let us know.

Regarding the part of the dialects, I am afraid there is not an "[official hibernate dialect](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/dialect/package-summary.html)" for AzureSQL which is not exactly MS SQL, and it's not about randomly adding all dialects from different databases to the project pom.xml (which adds unnecessary jars to the final artifact).
The other aspect is that
[https://hapi.fhir.org/baseR4/ServiceRequest?_sort=**p**atient:subject.name](https://hapi.fhir.org/baseR4/ServiceRequest?_sort=patient:subject.name)
is not the same as
[https://hapi.fhir.org/baseR4/ServiceRequest?_sort=**P**atient:subject.name](https://hapi.fhir.org/baseR4/ServiceRequest?_sort=Patient:subject.name) ;)

**Comment by XcrigX** [comment]
@jalbertoa  - AzureSQL is basically a managed SQL Server. I'm sure there are some architectural differences, but the query engine and SQL Syntax to my knowledge are not radically different - and certainly not for the basic SQL statements that are needed by HAPI. Anyway, I've connected many different Java applications to AzureSQL using the SQLServer2012Dialect dialect, and not had a problem. 

I see the language about removing the dialect for SQL Server was added with this PR: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/451
Looks like it was a mistake to include that under the SQL Server config section as that PR was about Postgres. @Kai-W ?

**Comment by Kai-W** [comment]
I probably wanted to hint to removing the default H2Dialect if SQL is used:
From the default application.yaml:
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/8ef50832d3459d4eb35ecb4f116c580475acb59d/src/main/resources/application.yaml#L32
