### ISSUE TITLE
Master branch does not compile

### ISSUE THREAD

**Issue by cyberoblivion** [hapifhir/hapi-fhir-jpaserver-starter#56]
Maven fails to build the master branch due to this error.
Failure to find ca.uhn.hapi.fhir:hapi-deployable-pom:pom:4.0.0-SNAPSHOT

Do I need to add a repository to my settings.xml or something?

**Comment by jamesagnew** [comment]
Ah shoot. There was an issue with the 4.0.0 release of HAPI (it still had a snapshot dependency) and we released 4.0.3 to correct that, but this project didn't get updated.

Will fix now.
