### ISSUE TITLE
Cannot run app locally

### ISSUE THREAD

**Issue by stormxa-i8c** [hapifhir/hapi-fhir-jpaserver-starter#574]
After checking out the code from Github, I am unable to run the app either with Jetty, spring-boot:run or spring-boot:repackage. I have not altered anything in the code, except changing the Java version in pom.xml to 17:
```
<properties>
    <java.version>17</java.version>
    <logback-classic.version>1.2.11</logback-classic.version>
    <slf4j-api.version>1.7.25</slf4j-api.version>
</properties>
```
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
    <configuration>
        <release>17</release>
    </configuration>
</plugin>
```
The version of Jetty is 10.0.14 and the Spring Boot version is 2.7.11.

When running with `mvn jetty:run`, the program runs, but with the following error:
`
Failed startup of context o.e.j.m.p.MavenWebAppContext@350e3fb4{/,[file:///C:/Users/stormxa/Downloads/hapi-fhir-jpaserver-starter-master/hapi-fhir-jpaserver-starter-master/src/main/webapp/, file:///C:/Users/stormxa/Downloads/hapi-fhir-jpaserver-starter-master/hapi-fhir-jpaserver-starter-master/target/jetty_overlays/hapi-fhir-testpage-overlay-6_6_0_war/, file:///C:/Users/stormxa/Downloads/hapi-fhir-jpaserver-starter-master/hapi-fhir-jpaserver-starter-master/target/jetty_overlays/jaxb-samples-2_3_5_zip/, file:///C:/Users/stormxa/Downloads/hapi-fhir-jpaserver-starter-master/hapi-fhir-jpaserver-starter-master/target/jetty_overlays/jaxb-release-documentation-2_3_5-docbook_zip/, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/npm/popper.js/1.16.1/popper.js-1.16.1.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/swagger-ui/4.1.3/swagger-ui-4.1.3.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/bower/moment/2.27.0/moment-2.27.0.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/npm/bootstrap/4.5.2/bootstrap-4.5.2.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/font-awesome/5.8.2/font-awesome-5.8.2.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/jstimezonedetect/1.0.6/jstimezonedetect-1.0.6.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/popper.js/2.9.3/popper.js-2.9.3.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/Eonasdan-bootstrap-datetimepicker/4.17.47/Eonasdan-bootstrap-datetimepicker-4.17.47.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/bootstrap/5.1.3/bootstrap-5.1.3.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/select2/4.0.13/select2-4.0.13.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/bower/awesome-bootstrap-checkbox/1.0.2/awesome-bootstrap-checkbox-1.0.2.jar!/META-INF/resources, jar:file:///C:/Users/stormxa/.m2/repository/org/webjars/bower/jquery/3.5.1/jquery-3.5.1.jar!/META-INF/resources],UNAVAILABLE}{file:///C:/Users/stormxa/Downloads/hapi-fhir-jpaserver-starter-master/hapi-fhir-jpaserver-starter-master/src/main/webapp/}
`

When I open the browser at http://localhost:8080/fhir/metadata, I get the following:

![Screenshot (30)](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/124668095/4489b355-2a5c-4c78-9300-6e2c7903317d)

When I run the app with `mvn clean spring-boot:run -Pboot`, I get the following error:

```
[WARNING] 
[WARNING] Plugin validation issues were detected in 4 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.8.1
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:3.1.0
[WARNING]  * org.apache.maven.plugins:maven-enforcer-plugin:3.0.0
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.7.11:run (default-cli) on project hapi-fhir-jpaserver-starter: Could not exec java: Cannot run program "C:\Users\stormxa\.jdks\azul-17.0.8\bin\java.exe" (in directory "C:\Users\stormxa\Downloads\hapi-fhir-jpaserver-starter-master\hapi-fhir-jpaserver-starter-master"): CreateProcess error=206, The filename or extension is too long -> [Help 1]
```

When running the app with `mvn clean package spring-boot:repackage -Pboot && java -jar target/ROOT.war`, I get the following error:

`Unable to parse command line options: Unrecognized option: -jar`

None of the tests work either, due to the following error:

`java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder`

I'm executing these commands from IntelliJ Community Edition, if that helps. I can't find anything useful in existing issues.

**Comment by XcrigX** [comment]
Try running the commands separately. 
_mvn clean package spring-boot:repackage -Pboot_
then:
_java -jar target/ROOT.war_

**Comment by stormxa-i8c** [comment]
Hi,

After running `mvn clean package spring-boot:repackage -Pboot`, it outputs an error: "There are test failures". This is the same message as when running individual tests.

**Comment by XcrigX** [comment]
Interesting.  I just cloned a fresh copy of the project and did not get any failures. There are only 2 tests that run currently, CustomBeanTest and CustomInterceptorTest (the rest of the tests are integration tests that don't run in the package phase). Are there any details about what failed?

**Comment by stormxa-i8c** [comment]
After re-running the jetty:run command, I should specify that the main error that is reported is this: `java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder`

It seems it cannot find an implementation of SLF4J, even though the pom.xml contains the logback dependencies. I do not get any errors about missing dependencies from my local repository.

The only thing I removed was one logback dependency, because IntelliJ marked it as a duplicate. The logback-core has version 1.4.4, but the logback-classic dependency has version 1.2.11, as specified in the logback-classic.version property.

**Comment by XcrigX** [comment]
I think I would try undoing all the changes you've made to the POM, and see if it compiles. Then you can examine if the changes you are making are actually needed and/or why they are breaking the build.
