### ISSUE TITLE
docker-compose does not work with mysql:latest database

### ISSUE THREAD

**Issue by florian-j-auer** [hapifhir/hapi-fhir-jpaserver-starter#58]
I had a problem running docker-compose with the mysql database set as in the `docker-compose.yml`. As image, there is stated to use `mysql:latest`, which currently is version 8.0.11. That causes that the `hapi-fhir-jpaserver-start` container cannot establish a connection to the linked  `mysqld` in the `hapi-fhir-mysql` container.

A solution would be to set the used image to version 5 (`mysql:5`) in `docker-compose.yml`, or to change the dependency in `pom.xml` to 
```
<dependency>
		<groupId>mysql</groupId>
		<artifactId>mysql-connector-java</artifactId>
		<version>8.0.11</version>
</dependency>
```
The first option would also prevent further issues when the latest mysql version changes at the docker hub.

**Comment by jamesagnew** [comment]
The latter option seems like it makes the most sense. Would you be willing to submit a PR?

**Comment by florian-j-auer** [comment]
Yeah, I can do that. With the latter option, you mean the option of changing the `docker-compose.yml` or the change in `pom.xml`?

**Comment by jamesagnew** [comment]
Upgrading the pom seems like it keeps us more current, which I guess is a
good thing :)

sent from my phone.
