### ISSUE TITLE
`public.hfj_res_ver.res_text_vc` data type in PostgreSQL is currently `varchar(4000)`, setting application property `hapi.fhir.inline_resource_storage_below_size` does not change the size can be stored in DB

### ISSUE THREAD

**Issue by muhammad-levi** [hapifhir/hapi-fhir-jpaserver-starter#590]
![image](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/78334846/f55b0125-38a1-47a1-9e9f-15aaf72e2ea4)

I think the data type should be of `TEXT` to accomodate changes in `inline_resource_storage_below_size` application property

**Comment by jkiddo** [comment]
@muhammad-levi thats a HAPI Core thing. Please report it at https://github.com/hapifhir/hapi-fhir
