### ISSUE TITLE
The server allows creating new instances of StructDefinition with the same URL.

### ISSUE THREAD

**Issue by nogueiralegacy** [hapifhir/hapi-fhir-jpaserver-starter#592]
When you attempt to submit an instance of StructDefinition (profile) with a POST operation, the server allows instances of StructDefinition to have the same URL. According to the FHIR R4 specification, instances of the same StructDefinition can have the same URL but in different versions. Therefore, creating another one is not a correct implementation according to the specification.

**Comment by jkiddo** [comment]
Feel free to make a PR that e.g. generates a conditional create on a SearchParameter up startup that makes the StructureDefintion.Url a unique index - see e.g. https://support.smilecdr.com/space/SK/2575073302/How+To%3A+Enforce+Uniqueness+For+A+Given+identifier+System+Value+Across+All+Resources+of+a+Particular+Type
