### ISSUE TITLE
Build image locally

### ISSUE THREAD

**Issue by htaimoor2010** [hapifhir/hapi-fhir-jpaserver-starter#596]
I need to add some custom interceptors in hapi fihr. I have cloned this repo and have added a new module hapi-fihr-custom-interceptors and have defined my interceptor classes in it. Now I need to build an image locally instead of pulling from 
 **hapiproject/hapi:latest**. Do we have an example of such docker file? I am not sure where should I copy my new module.

**Comment by XcrigX** [comment]
You can just use the Dockerfile in this project I would think: 
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/Dockerfile

Or if you want to use the published HAPI docker image, this may provide some clues on how to add your custom interceptors into the container: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/534#issuecomment-1735350261
