### ISSUE TITLE
release hapi-fhir-jpaserver-starter Jitterbug (4.1.0)

### ISSUE THREAD

**Issue by johnpoth** [hapifhir/hapi-fhir-jpaserver-starter#61]
Looks like the 4.1.0 wasn't [released](https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-jpaserver-starter/4.1.0) ? Thanks !

**Comment by jamesagnew** [comment]
I see it both in Maven Central and this project's GitHub releases section- What is missing?

**Comment by johnpoth** [comment]
Hi James, I can see
v4.0.0 : https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-jpaserver-starter/4.0.0
But not v4.1.0 which I guess should be here:
https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-jpaserver-starter/4.1.0

Thanks !

**Comment by jamesagnew** [comment]
Seems like an issue with that website - The release is definitely out. See:

https://search.maven.org/search?q=hapi-fhir-jpaserver-starter

(Ps- Do people still use mvnrepository.com? I gave up on it ages ago, given how much more usable search.maven.org is)

**Comment by johnpoth** [comment]
Hi James closing as it is present
https://repo1.maven.org/maven2/ca/uhn/hapi/fhir/hapi-fhir-jpaserver-starter/4.1.0/
but Maven central did not update yet ...
https://mvnrepository.com/artifact/ca.uhn.hapi.fhir/hapi-fhir-jpaserver-starter/4.1.0

I think people still use mvnrepository.com but I'll give search.maven.org a try now for sure :+1: 

Thanks !
