### ISSUE TITLE
Externalization of the application.yaml in Docker

### ISSUE THREAD

**Issue by psavva** [hapifhir/hapi-fhir-jpaserver-starter#631]
I would like to allow the externalization, and thus changes in configuration of the application.yaml configuration file.
This can be achieved using a bind volume.

@jkiddo

**Comment by jkiddo** [comment]
Its supported already. There's an example on https://github.com/hapifhir/hapi-fhir-jpaserver-starter?tab=readme-ov-file#configuration-via-overridden-applicationyaml-file-and-using-docker

**Comment by psavva** [comment]
Fair enough, closing
