### ISSUE TITLE
SubscriptionWebsocketHandler to deliver ResourceDeliveryMessage if full-resource content

### ISSUE THREAD

**Issue by ArtyomyuS** [hapifhir/hapi-fhir-jpaserver-starter#638]
Hello there dear community.
I was looking into the Websocket handling of the subscriptions and try to figure out if one aspect of the implementation was done properly.

Accordingly to R5 standard  https://hl7.org/fhir/subscription.html on managing a subscription: `By adjusting Subscription.content, subscribers can request event notifications that include full resource content; or just the ID of the triggering resource; or an empty notification body.`

Does it make sense to open a pull request that will update current code for `SubscriptionWebsocketHandler` so that:
if `msg.getSubscription()` has `content` = `id-only` to deliver(msg.getPayloadId()) and in case of `content` = `full-reference` to invoke `deliver(msg.getPayload())

Please advice if this is appropriate.

Thank you

**Comment by ArtyomyuS** [comment]
Hi there, any update on this?

**Comment by KevinDougan-SmileCDR** [comment]
Hi @ArtyomyuS ,

This Issue here can be **Closed** since [James mentioned](https://github.com/hapifhir/hapi-fhir/issues/5687#issuecomment-1932730524) that this can be addressed in the [HAPI-FHIR](https://github.com/hapifhir/hapi-fhir) repository.
