### ISSUE TITLE
Setting "Server ID Strategy" to UUID from config seems confusing and undocumented

### ISSUE THREAD

**Issue by joshuagrisham-karolinska** [hapifhir/hapi-fhir-jpaserver-starter#649]
Hello!

For security reasons, and especially for certain resource types, we have a very strong desire to make sure that new Resource Ids should not really be possible to figure out without knowing them in advance (as is the case with a UUID, for example, and not the case with sequential numbers), so the UUID [Server ID Strategy](https://hapifhir.io/hapi-fhir/docs/server_jpa_partitioning/partitioning.html#partitioning-and-resource-ids) is a really good fit!

However, with this starter project I had a bit of a tough time figuring out exactly how you could set it via config, and just managed to stumble upon a few lines of code in the config class [FhirServerConfigCommon](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/9e21d8062e84499a2e233a0463990452da3c2aba/src/main/java/ca/uhn/fhir/jpa/starter/common/FhirServerConfigCommon.java#L176-L177) which makes it so that if I happen to set [hapi.fhir.client_id_strategy](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/9e21d8062e84499a2e233a0463990452da3c2aba/src/main/resources/application.yaml#L136) to the value "ANY" then we can achieve the end result of having this ResourceServerIDStrategy set to UUID.

When I read further in the core HAPI FHIR docs then I can see that this Client ID Strategy is more about what clients will be **_allowed_** to send as new Resource Ids (as opposed to what comes from the server by default when no new Id is specified e.g. if you create a resource using the REST API with `POST`) and that when using the [ANY](https://hapifhir.io/hapi-fhir/apidocs/hapi-fhir-storage/undefined/ca/uhn/fhir/jpa/api/config/JpaStorageSettings.ClientIdStrategyEnum.html#ANY) Client ID Strategy it is strongly recommended to also use UUID as the Server ID Strategy, but not that it is necessarily required?

With that understanding then it seems that only allowing the to set `client_id_strategy` with `FhirServerConfigCommon` then it is making an opinionated change on the Server ID Strategy that we don't have a way to modify (and, by the way, there seems to be no other way to change the Server ID Strategy except for this?).

Is it possible that a new config property `server_id_strategy` could be created which allows both to be controlled separately from each other via config ? (and possibly, as it is today, if someone sets `client_id_strategy`=ANY and does not set `server_id_strategy` then it could default to UUID, and if set to something other than UUID in this case, a bonus could be to print a warning in the log?)

**Comment by jamesagnew** [comment]
FWIW, the Server ID Strategy isn't deliberately omitted from the starter project or anything. Often we add new configurability options to HAPI FHIR and then they only get added as YAML-configurable settings in the starter project when someone needs them.

A PR adding such a setting would certainly be accepted.

**Comment by joshuagrisham-karolinska** [comment]
Done @jamesagnew , please feel free to take a peek at #653 if you want and see how it looks 😉

**Comment by jamesagnew** [comment]
Awesome! Closing this now.
