### ISSUE TITLE
Unable to fetch Encounter by Patient Identifier

### ISSUE THREAD

**Issue by daya** [hapifhir/hapi-fhir-jpaserver-starter#66]
I have this patient http://hapi.fhir.org/baseR4/Patient?identifier=CERNER-DRMC-008010210&_pretty=true and I created this Encounter on it http://hapi.fhir.org/baseR4/Encounter/181221?_pretty=true

But I am unable to search this Encounter by internal/business Patient Identifier i.e. this does not work http://hapi.fhir.org/baseR4/Encounter?patient.identifier=CERNER-DRMC-008010210| 

is there any other way to list encounters by a given Patient business Identifier

**Comment by jamesagnew** [comment]
Only seach by reference is currently supported. You need to change the reference on your Encounter to be "reference":"Patient/181221" instead of using the business identifier there.

**Comment by daya** [comment]
Interestingly enough Encounter can be created using "subject" of type "identifier" which is in compliance with FHIR v4. Does this mean HAPI is not fully compliant with FHIR version 4 ?

**Comment by daya** [comment]
@patrick-werner I thought you wanted me to create this issue but it seems this is not even a bug.

**Comment by jamesagnew** [comment]
Technically I don't think that search was valid for the data you have stored either way... If you're using a chain (i.e. patient.identifier) then there needs to be a resource reference if I am reading the spec correctly.

**Comment by daya** [comment]
@jamesagnew since I stored the Encounter with Subject --> Identifier I tried to do search with even `subject.identifier` like this http://hapi.fhir.org/baseR4/Encounter?subject.identifier.value=CERNER-DRMC-008010210| but even that did not return the result. According to @patrick-werner  this is a bug, so @jamesagnew could you please re-open this comment and label it is a bug

**Comment by patrick-werner** [comment]
http://hapi.fhir.org/baseR4/Encounter?patient.identifier=http://new-republic.gov/galactic-citizen-identifier|000000000
works. Encounter is referencing Patient via ?patient
I guess the „%“ in the identifier value are causing the trouble here (weird that escaping seems to work when using ?identifier directly on Patient)
@jamesagnew would you be ok to move this issue to the hapi-fhir repo?

**Comment by daya** [comment]
@patrick-werner the problem is much more involved/subtle than that see this url does not work http://hapi.fhir.org/baseR4/Encounter?patient.identifier=http://caringly.tech/hospital-patient-identifier|CERNER-DRMC-008010210

while this http://hapi.fhir.org/baseR4/Patient?identifier=CERNER-DRMC-008010210&_pretty=true and this point to the same patient resource http://hapi.fhir.org/baseR4/Patient?identifier=000000000&_pretty=true

so why does Encounter work with one identifier and not the other even though `%` sign is not being used?

**Comment by daya** [comment]
@patrick-werner I think I figured it out. Apparently the right way to query Encounter by Patient Identifier is this http://hapi.fhir.org/baseR4/Encounter?subject:Patient.identifier=CERNER$DRMC$008010210 only if the Encounter was created with `subject.reference` **like [this](https://gist.github.com/daya/c46fc3b6ab500a338e9f53d49644db34#file-encounter-subject-reference-json-L74)** and not with `subject.identifier` which makes sense

apparently [RTFM](http://www.hl7.org/fhir/search.html#chaining) helps :wink:

**Comment by patrick-werner** [comment]
@daya yes you have to use subject reference, like you did here:
http://hapi.fhir.org/baseR4/Encounter/160434

This works:
http://hapi.fhir.org/baseR4/Encounter?patient.identifier=http://new-republic.gov/galactic-citizen-identifier%7C000000000

This does not work:
http://hapi.fhir.org/baseR4/Encounter?_type=Patient&identifier=http://caringly.tech/hospital-patient-identifier|DRMC%25CERNER%250194667871

which leaves me thinking that `%`messes up the parameter parser when you use it in a chained search.

**Comment by jamesagnew** [comment]
That second URL is a search for encounters with the identifier you list, not chained patients.

You probably want this: http://hapi.fhir.org/baseR4/Encounter?patient.identifier=DRMC%25CERNER%250194667871

**Comment by patrick-werner** [comment]
> That second URL is a search for encounters with the identifier you list, not chained patients.
Oh i did a c&p error, you are right. edited my post.

**Comment by jamesagnew** [comment]
the edited url works though, yeah?

**Comment by patrick-werner** [comment]
> the edited url works though, yeah?

you are right, i must have confused the id value yesterday night.
