### ISSUE TITLE
Identifier Token search

### ISSUE THREAD

**Issue by shmightworks** [hapifhir/hapi-fhir-jpaserver-starter#683]
I've just spun up a fresh jpa starter server.

POSTed a simple patient:
{
    "resourceType": "Patient",
    "identifier": [{
            "use": "official",
            "type": {
                "coding": [{
                        "system": "http://hl7.org/fhir/v2/0203",
                        "code": "JHN",
                        "display": "Jurisdictional health number (Canada)"
                    }
                ]
            },
            "system": "https://fhir.infoway-inforoute.ca/NamingSystem/ca-on-patient-hcn",
            "value": "0000000018"
        }
    ],
    "name": [{
            "use": "official",
            "family": "Test",
            "given": [
                "Test"
            ]
        }
    ],
    "gender": "male",
    "birthDate": "1990-01-01"
}

I tried to search up this patient with this, but it's not returning the patient:
fhir/Patient?identifier=http%3A%2F%2Fhl7.org%2Ffhir%2Fv2%2F0203%7CJHN%3A0000000018
This doesn't work either:
fhir/Patient?identifier=JHN%3A0000000018
Nor this:
fhir/Patient?identifier=http%3A%2F%2Fhl7.org%2Ffhir%2Fv2%2F0203%7C0000000018
Only this works:
fhir/Patient?identifier=0000000018

This should be a standard FHIR search:
https://hl7.org/fhir/search.html#token

Am I missing some settings or doing the search wrong?

Thanks

**Comment by shmightworks** [comment]
Ok, I sorted out the issue, seems the query I was given was doing something weird.
The system and code should be of the same "level", and the query somehow was doing a mix of that.
Need to sort this out with the vendor.

**Comment by shmightworks** [comment]
Reading further into the specs' wording, seems like this is an issue afterall.
If I do a search with this:
fhir/Patient?identifier=http%3A%2F%2Fhl7.org%2Ffhir%2Fv2%2F0203%7C0000000018
system is http://hl7.org/fhir/v2/0203
code is 0000000018
I should get a result even though the system and code is not in the same "level".

Here's the blurb from hl7:
[parameter]=[system]|[code]: the value of [code] matches a Coding.code or Identifier.value, and the value of [system] matches the system property of the Identifier or Coding

So both the system and the code could belong to either the identifier level or the coding level.

**Comment by XcrigX** [comment]
When searching on an Identifier, only the Identifier.system and Identifer.value are considered. The Identifier.type.x attributes are not considered. This is not a bug. 

You could create a custom search parameter to also search on Identifier.type if desired, but that is not part of the FHIR spec.

**Comment by shmightworks** [comment]
Here's where I'm reading it again:

https://www.hl7.org/fhir/search.html#token
[parameter]=[system]|[code]: the value of [code] matches a Coding.code or Identifier.value, and the value of [system] matches the system property of the Identifier or Coding

The part about Coding.code or Coding, isn't it referring to the Identifier.type.Coding.code?

**Comment by XcrigX** [comment]
No. If you scroll down in that section there is a table that shows you the attributes that will be considered for a given datatype. 

However, I see now that you may be able to use the ":of-type" modifier to also include the type information (I didn't know that). 
see: https://www.hl7.org/fhir/search.html#modifieroftype

I don't know if HAPI supports ":of-type" though.

**Comment by shmightworks** [comment]
Ah, gotcha, thanks.
Putting that blurb on here as well for reference:

Identifier	Identifier.system	Identifier.value	Clients can search by type not system using the :of-type modifier, see below. To search on a CDA II.root - which may appear in either Identifier.system or Identifier.value, use the syntax identifier=|[root],[root]

Just want to make sure whatever my vendor's asking is not of spec.

**Comment by marceloabrumet** [comment]
I'm not sure if you were dealing with the same problem as me, but I had to add this to the application.yaml because I was having some problems with the conversion of the query characters when adding the parameter identifier=system|code :

server:
  tomcat:
    relaxed-query-chars: '|,{,},[,],^'
