### ISSUE TITLE
Unable to enable CR module

### ISSUE THREAD

**Issue by farmaan-e** [hapifhir/hapi-fhir-jpaserver-starter#688]
I am unable to start the CR module. Getting  `CrConfigCondition not met: Missing RestfulServer bean` in the lastest docker image `7.2.0`

I have added following properties
```
 cr:
      enabled: true
 fhir_version: R4
```

**Comment by barhodes** [comment]
Keep an eye on this branch: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/tree/br-cs-merged

The wireup issues should all be resolved in this branch and we are working to get it ready to be merged.
