### ISSUE TITLE
Support multiple FHIR versions [DISCUSS]

### ISSUE THREAD

**Issue by johnpoth** [hapifhir/hapi-fhir-jpaserver-starter#70]
Hello,

When testing, we often need to validate against all FHIR versions. Right now the way we do it is to spin up multiple FHIR servers each having a different version. Only one FHIR version per server is currently supported here.

I'm not sure whether it makes sense to support multiple versions of FHIR beyond testing purposes ? If not then I don't think it's worth the effort.

Thanks !

**Comment by seanmcilvenna** [comment]
I believe @jamesagnew has talked about supporting a single server with multiple endpoints for each version of FHIR configured... Can you confirm @jamesagnew ?

**Comment by jamesagnew** [comment]
The public server works this way ( hapi.fhir.org ) but I don't know that it makes sense in this context of this project... I can see how it would be useful for testing use cases, but it would significantly complicate the project which reduces its utility as a starting point for people implementing the JPA server

**Comment by seanmcilvenna** [comment]
For the record, @jamesagnew , I would love this functionality :) I have to setup two different installations of HAPI in Lantana's environment to support STU3 and R4 for Trifolia-on-FHIR. I would love to simplifying that deployment to just a single installation.

**Comment by patrick-werner** [comment]
as this is open for quite a while, and is a very specific use-case. I'm closing this one here.
