### ISSUE TITLE
Maven Build Fails

### ISSUE THREAD

**Issue by stewart-anderson** [hapifhir/hapi-fhir-jpaserver-starter#702]
Hi,  I haven't built anything java in well over 10 years and still new to maven really.

I imported the HAPI FHIR project to Intellij Ultimate and want to run it in Tomcat.   The build fails with a deprecated maven attribute.  

` 
Parameter 'forceJavacCompilerUse' (user property 'maven.compiler.forceJavacCompilerUse') is deprecated: Use forceLegacyJavacApi instead
`

This is apparently in the testcases POM, which is read only as its a dependency - I assume!   Wondering why  Maven is giving me this if netbeans doesn't?  I'm thinking that to continue I should just get the sources for everything and fix locally, or should the HAPI FHIR dependencies be fixed ?  

**Building in mvn CLI gives a different error:** 
`[INFO] ------------< ca.uhn.hapi.fhir:hapi-fhir-jpaserver-starter >------------
[INFO] Building HAPI FHIR JPA Server - Starter Project 7.2.1
[INFO]   from pom.xml
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- clean:3.1.0:clean (default-clean) @ hapi-fhir-jpaserver-starter ---
[INFO] Deleting C:\Users\Stewart\IdeaProjects\hapi-fhir-jpaserver-starter\target
[INFO]
[INFO] --- enforcer:3.3.0:enforce (enforce-maven) @ hapi-fhir-jpaserver-starter ---
[INFO] Rule 0: org.apache.maven.enforcer.rules.version.RequireMavenVersion passed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.617 s
[INFO] Finished at: 2024-06-24T12:53:48+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce (enforce-maven) on project hapi-fhir-jpaserver-starter:
[ERROR] Rule 1: org.apache.maven.enforcer.rules.version.RequireJavaVersion failed with message:
[ERROR] HAPI FHIR is targeting JDK 11 for published binaries,
[ERROR]                                                                                 but we require JDK 17 to build and test this library.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

It builds in netbeans, was looking to use Intellij, since I am paying for it (use other tools from JetBrains) 

I know this isn't really an issue with HAPI FHIR Started, rather my build environment,  just seeking guidance on how more experienced/seasoned out there would deal with it.  

Thanks

**Comment by jamesagnew** [comment]
You need to use Java 17 to build this project, and Maven is failing because you're running a lower version. Run `mvn -version` to see what version of Java is currently available to Maven. SDKMAN might be a helpful tool if you need help getting a newer JDK installed.

Note also - Please don't use github issues to ask questions about HAPI FHIR. See this wiki page for how to ask for help: https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help

**Comment by stewart-anderson** [comment]
Slightly embarrassed,  I did look at the  maven version but only to get the maven tool version itself, didn't see the java version at all.  Noted on the help requests,  thank you for responding.
