### ISSUE TITLE
Azure AD Integration

### ISSUE THREAD

**Issue by michael-gvdw** [hapifhir/hapi-fhir-jpaserver-starter#705]
Does the project allow for azure ad integration? if so, how? How would i develop the auth interceptor and what do i need to configure? Would i need to alter the source code?

**Comment by KevinDougan-SmileCDR** [comment]
Hi there,

Smile CDR is an Enterprise-ready solution which provides this capability in a supported release:

https://smilecdr.com/docs/security/security_in_smile_cdr.html

Also, please don't open a github issues to ask questions about HAPI-FHIR.
See this wiki page for how to ask for help:

https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help
