### ISSUE TITLE
Custom Logo and Welcome Html

### ISSUE THREAD

**Issue by TakasiSHIH** [hapifhir/hapi-fhir-jpaserver-starter#709]
I have tried to add "custom_content_path: ./custom" string to application.yaml.
But my fhir server is still show default icon and welcome html.
Can give some idea for this? Thank you!!!

=====================================
![圖片](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/assets/3366038/0a27fdee-ef45-4fe3-8552-84e583bda831)

**Comment by joofio** [comment]
did you map that volume in the docker run / docker compose ?

Then add the logo as logo.jpg

**Comment by joofio** [comment]
1. the custom path is under hapi.fhir....not tester i believe.
2. i would just use the example path (custom) and then map it outside to where you want it to be

like:
```
   - hapi.fhir.custom_content_path=/custom
```
volumes:
  - <where you have things>:/custom

**Comment by TakasiSHIH** [comment]
HI joofio

Sorry...
Where I should put string: "- hapi.fhir.custom_content_path=/custom" ?
"docker-compose.yml" or "application.yaml" ?

**Comment by TakasiSHIH** [comment]
> application.yaml like in the example
> 
> https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/19f1e2208ed003e68f17fd127a3a1efed0ba40f7/src/main/resources/application.yaml#L142

application.yaml
Line 142

I also have tried this two days ago.
It did still not work. XDDDD

**Comment by joofio** [comment]
i have a setup like this and works just fine.
custom_content_path: ./custom on application.yml

volume like myfolder:/custom (not the other way around)
and logo.jpg in myfolder

is the application.yml being taken into account?

**Comment by TakasiSHIH** [comment]
> i have a setup like this and works just fine. custom_content_path: ./custom on application.yml
> 
> volume like myfolder:/custom (not the other way around) and logo.jpg in myfolder
> 
> is the application.yml being taken into account?

Thank you joofio!!!
It's work!!!

**Comment by Suprakash001** [comment]
> i have a setup like this and works just fine. custom_content_path: ./custom on application.yml
> 
> volume like myfolder:/custom (not the other way around) and logo.jpg in myfolder
> 


> is the application.yml being taken into account?

Hi joofio,

Hope doing good!!!
I have tried what you have suggested. But didn't get succeeded. Could you please verify my files and help me?
[HAPI.zip](https://github.com/user-attachments/files/16632702/HAPI.zip)

**Comment by TakasiSHIH** [comment]
> > i have a setup like this and works just fine. custom_content_path: ./custom on application.yml
> > volume like myfolder:/custom (not the other way around) and logo.jpg in myfolder
> 
> > is the application.yml being taken into account?
> 
> Hi joofio,
> 
> Hope doing good!!! I have tried what you have suggested. But didn't get succeeded. Could you please verify my files and help me? [HAPI.zip](https://github.com/user-attachments/files/16632702/HAPI.zip)

You can modify the file [hapi.application.yaml] and try it.
custom_content_path: **./custom** to  custom_content_path: **/custom**

In my case:

[ docker-compose.yml ]
volumes:
      - ./custom:/custom

[ hapi.application.yaml ]
custom_content_path: /custom
