### ISSUE TITLE
The data cannot be found in the database.

### ISSUE THREAD

**Issue by 1unasy** [hapifhir/hapi-fhir-jpaserver-starter#736]
We have developed HAPI-FHIR following the steps below;
1. To build FHIR database with PostgreSQL
2. To clone HAPI-FHIR github repository and modify docker-compose.yaml & hapi.application.yaml
3. To compose docker file
4. To run HAPI-FHIR server with local-host
5. To upload Samples and find errors

Our HAPI-FHIR was built as follows;
MIMIC: 2.2 version
FHIR: 2.0 version

Error:
Data cannot be found in the database even if there is data uploaded to the server.

Detail:
we uploaded and checked the patient data at the server.

But the data cannot be found in our database.

So we searched and found that the FHIR server was developed as the schema of MIMICIV version 2.0.

Therefore, we think the other version is the cause of the error and would like to ask you if there is a specific FHIR schema for MIMICIV version 2.2.

If not, what do you think the cause of the error?
Please let me know how to handle the error.

Thank you.

**Comment by jamesagnew** [comment]
This is not enough information to be able to do anything with it unfortunately.

Please provide a minimum reproducible example - ie supply the absolute minimal dataset required to demonstrate the issue (ideally a single resource, only multiple resources if you have confirmed that they are required in order to trigger the issue), along with the exact commands you are using to upload and query the data, and the response you are expecting.

**Comment by 1unasy** [comment]
[HAPI_FHIR_FOR_Github.pdf](https://github.com/user-attachments/files/16971810/HAPI_FHIR_FOR_Github.pdf)

I've attached a pdf file written on how to develop DB.

I checked all database I had, and I could not find datas that had uploaded at the server.

**Comment by jamesagnew** [comment]
The data is uploaded successfully as shown in your screenshot of the HAPI FHIR testing UI.

I don't know what that `mimiciv_hosp` table is, but it's not a part of HAPI FHIR, so it won't be populated by HAPI FHIR. In other words, the HAPI FHIR JPA server writes to its own tables in the database, and those tables aren't intended to be read/written directly, only via the API.

If you need to populate third-party tables, you are probably looking for the HAPI FHIR plain server and you'll need to write storage logic to populate them.

**Comment by jamesagnew** [comment]
Oh wait, I just realized the URL of the project you cloned: https://github.com/kind-lab/mimic-fhir

You'd have to open a ticket against that project to ask what it's doing. This github repository is for the HAPI FHIR JPA server, not that server.

**Comment by 1unasy** [comment]
So do you mean that I need to ask that github(https://github.com/kind-lab/mimic-fhir) to handle this error??

Thank you for your quick and kind response :-)
