### ISSUE TITLE
Overriding properties using Environment variables

### ISSUE THREAD

**Issue by daya** [hapifhir/hapi-fhir-jpaserver-starter#74]
I am running JPA Starter Server using Docker and looking for a way to specify `datasource.url` using environment variable, so far I have tried using 

```
datasource.url=${POSTGRES_URL}
```
in properties file. And setting corresponding environment variable using `docker run -e POSTGRES_URL=jdbc:postgresql://XXXX:5432/hapi` but this does not work.

Any idea on how to make it work? 

Do I need to provide my custom implementation ? or is there a system property I can override (I am not a Java pro so I may be missing something obvious to everyone else)

**Comment by snimmagadda1** [comment]
Use java env var like System.getenv

**Comment by snimmagadda1** [comment]
I’ve done something similar by modifying the HapiProperties.java and used System.getenv()

**Comment by daya** [comment]
@snimmagadda1 short of changing HapiProperties.java I was looking for an easier solution and I found one but it was reverted back by @jamesagnew for some reason (not mentioned) https://github.com/hapifhir/hapi-fhir-jpaserver-starter/commit/ef828e66bb27e3f6ec9717cd608cba3129377d3a#r36543626

**Comment by jamesagnew** [comment]
FYI that commit was just me merging PR #69, I don't think the intention was specifically to break docker workflow, but this is a tough thing to get right.

Maybe the right solution here is to modify HapiProperties.java so that absolutely any of the properties in there can be overridden via an environment variable?

**Comment by snimmagadda1** [comment]
I think modifying `HapiProperties.java` such that any property could be overridden is definitely a workable solution. But I'm wondering if implementing it would clutter `HapiProperties.java` too much, or is that a non issue?

i.e this
```
public static boolean isElasticSearchEnabled() {
        return HapiProperties.getPropertyBoolean("elasticsearch.enabled", false);
    }
```

would become this:
```
    public static boolean isElasticSearchEnabled() {
        if(System.getenv("ELASTICSEARCH_ENABLED") != null){
            return Boolean.parseBoolean(System.getenv("EELASTICSEARCH_ENABLED"));
        }
        return HapiProperties.getPropertyBoolean("elasticsearch.enabled", false);
    }
```

Even with the use of ternaries, it might get out of hand pretty quickly... Unless there's a more elegant way to do the above?

**Comment by jamesagnew** [comment]
I would think putting the logic in `getPropertyBoolean` etc would be
easier..

**Comment by patrick-werner** [comment]
Sorry a bit late to the topic. But do we really need a modification to the existing status? We are overwriting the properties file with a tomcat context file. So we can deploy the same war everywhere, but have persistent, vm bound properties.

On Ubuntu this:
```.xml
<Context>
	<Parameter name="server_address" value="https://demo.molit.eu/fhir" />
	<Parameter name="datasource.url" value="jdbc:postgresql://localohst:5432/fhir" />
	<Parameter name="datasource.username" value="fhir" />
	<Parameter name="datasource.password" value="bu-ba-bi-herebo" />
</Context>```
Has to be stored (Ubuntu)  here: /etc/tomcat8/Catalina/localhost/[WAR_NAME].xml

This overwrites the hapi db properties provided inside the war file.
For docker usage i just would link/copy this properties file into the docker container.

**Comment by lburgazzoli** [comment]
Isn't this already done by https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java#L162-L178 ?

**Comment by seanmcilvenna** [comment]
I agree. I think this is also documented here: https://github.com/hapifhir/hapi-fhir-jpaserver-starter#overriding-properties

**Comment by jrschremmer** [comment]
> Isn't this already done by https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java#L162-L178 ?

@lburgazzoli @seanmcilvenna  that code handles properties without a default value, but properties with a default value don't call that code.  I had the same problem and made a minor change (#78) to `HapiProperties` to make the processing consistent.

**Comment by seanmcilvenna** [comment]
Understood. Looks good. Merged the request.

**Comment by citizenrich** [comment]
Hi folks. Perhaps it's clear to folks with knowledge of Java, but does the method here make it possible to pass env vars or must the hapi.properties file be modified?
https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java#L166

**Comment by jamesagnew** [comment]
This is the line that loads the value from the environment if it exists:

https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/java/ca/uhn/fhir/jpa/starter/HapiProperties.java#L170

**Comment by seanmcilvenna** [comment]
James, can you provide guidance on how to override the "hibernate.dialect" property with this approach. The HapiProperties class doesn't explicitly make use of the "hibernate.dialect" property. It just passes the hapi.properties files' properties forward. So, I'm not really sure how one would use env variables to override those properties.

**Comment by citizenrich** [comment]
Thanks @jamesagnew. Here is the most minimal example in which I don't see HAPI picking up the env var:
```
docker run -e HAPI_FHIR_VERSION=DSTU3 -p 8080:8080 hapiproject/hapi:4.1
```
I still get R4. The reason I formatted it as HAPI_FHIR_VERSION is because what the code seems to do is append HAPI_ and replaces dots and dashes with underscores to do its comparison with env vars. So, HAPI_FHIR_VERSION should match with fhir_version.

Any thoughts? My goal is to change the port but the fhir version is just a minimal example.
