### ISSUE TITLE
Cannot Import US Core Profile

### ISSUE THREAD

**Issue by MattMorgis** [hapifhir/hapi-fhir-jpaserver-starter#76]
I am trying to import the structure definitions and value sets from the [US Core R4](https://github.com/HL7/US-Core-R4/tree/master/source/resources) profile on a fresh implementation of this HAPI starter server. 

The only change I've made is enabling validation on incoming requests here: https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/master/src/main/resources/hapi.properties#L50

I'm new to FHIR and unsure if this is an issue with how HAPI does validation or if there is something wrong with the actual structure definitions for US Core.

**Comment by jamesagnew** [comment]
@MattMorgis and @bkaney thanks for reporting! A fix has been made in the upstream project and will be pushed to maven central in the next 24 hours.

Note that you'll need to use branch `rel_4_2_0` of this project to get that fix, until we release 4.2.0 in Feb.

**Comment by MattMorgis** [comment]
@jamesagnew Was it pushed to maven? I am getting an error trying to load in `v4.2.0-SNAPSHOT`
