### ISSUE TITLE
response from ValueSet/$expand doesn't use the provided display values in the valueset concept

### ISSUE THREAD

**Issue by iceBuko** [hapifhir/hapi-fhir-jpaserver-starter#85]
Hi everyone,

I've been trying to figure this out.

As per  http://hl7.org/fhir/valueset.html#designations
when a display value is provided inside a concept, the expansion generated will use the display provided in the valueset.

But as seen below, the server returns the long common name from loinc.

Is there something i'm missing here?

This is my valueset
{
  "resourceType": "ValueSet",
   "url":"http://fhir.amsclinic.net/ams/ValueSet/ams-lab-chem-loinc-codes",
  "title": "AMS Laboratory Chemistry Loinc Order Codes",
  "name":"ams-lab-chem-loinc-codes",
  "status": "active",
  "compose":{
    "include":[
        {
            "system":"http://loinc.org",
            "concept":[
                {
                    
                    "code":"14771-0",
                    "display":"FBS"
                }
            ]
        }
    ]
    }
}

My get reuest  http://fhir.amsclinic.net/ams/ValueSet/$expand?url=ams-lab-chem-loinc-codes

the response
{
    "resourceType": "ValueSet",
    "status": "active",
    "compose": {
        "include": [
            {
                "valueSet": [
                    "ams-lab-chem-loinc-codes"
                ]
            }
        ]
    },
    "expansion": {
        "identifier": "6a67bedc-a05d-4e97-ac2d-2f2f5b0ea4e9",
        "timestamp": "2020-03-06T18:36:58+08:00",
        "total": 16,
        "contains": [
            
            {
                "system": "http://loinc.org",
                "code": "14771-0",
                "display": "Fasting glucose [Moles/volume] in Serum or Plasma",
                "designation": [
                    {
                        "use": {
                            "display": "ShortName"
                        },
                        "value": "Glucose p fast SerPl-sCnc"
                    }
                ]
            
            }
        ]
    }
}

I'm using 4.2.0.

Any help is appreciated.

Thanks

**Comment by iceBuko** [comment]
Ok sorry I figured it out.
use this request instead  http://fhir.amsclinic.net/ams/ValueSet/ams-lab-chem-loinc-codes/$expand?

Thanks

**Comment by seanmcilvenna** [comment]
This issue should be moved to https://github.com/jamesagnew/hapi-fhir
