### ISSUE TITLE
Support MariaDB compliant with Apache 2.0 license

### ISSUE THREAD

**Issue by carloscaverobarca** [hapifhir/hapi-fhir-jpaserver-starter#86]
# Feature Request

**Describe the Feature Request**

Support MariaDB compliant with Apache 2.0. MySQL connector has a different commercial use and it cannot be used freely.

**Is your feature request related to a problem? Please describe**

Cover DB connectors compliant with Apache 2.0 would spread the use of the component.

**Describe Preferred Solution**

Add the MariaDB connector to the maven pom. Modify the configuration of the server and provide a docker-compose for testing.

**Additional Context**

MariaDB client is available [here](https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client) and the docker image [here](https://hub.docker.com/_/mariadb)

**Comment by carloscaverobarca** [comment]
I can send you a PR with the proposed solution

**Comment by jamesagnew** [comment]
Sounds great, PR would be welcomed.

**Comment by carloscaverobarca** [comment]
Ok, I am working on it, hope to send this week

**Comment by carloscaverobarca** [comment]
I found some issues with the creation of sequences, HAPI starts and load the resources well but in MariaDB the SEQUENCES are created as TABLES, so when I search for the resouces error `SEQ_SEARCH is not a SEQUENCE` is raised (I supposed a lot of functionalities will also stop working for the same reason). Of course everything works if I remove the tables SEQ_XX and create the sequences manually, but it is not the ideal solution. @jamesagnew any hint that can help regarding the database creation I can have a look to understand why sequences are created as tables in MariaDB? Thanks!

**Comment by jamesagnew** [comment]
Is it possible we just need a newer/different dialect configured in
hibernate?

Older MySQL didn't support native sequences, so MariaDB probably didn't
either..

**Comment by carloscaverobarca** [comment]
Yes I considered this but I am using `org.hibernate.dialect.MariaDB103Dialect` and MariaDB 10.3 supports sequences. But probably you are right there are something missing in this direction. I will have a look and tell you something.

**Comment by carloscaverobarca** [comment]
Ok, now it is working, the problem is that when I firstly created the database schema, I used the MySQL dialect and something went wrong with MariaDB. I will upload a bunch of resources to test and send the PR. It seems everything is working like in MySQL (as expected).

**Comment by carloscaverobarca** [comment]
I tested loaded resources to the R4 instance and everything works as expected. I sent a PR, tell me if you need more clarifications/refinements.

**Comment by jkiddo** [comment]
Hi @carloscaverobarca - Would you consider rebasing your changes in order for us to have a look at your PR on https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/87?

**Comment by jkiddo** [comment]
Closing as inactive
