### ISSUE TITLE
docker-compose build takes really long and fails

### ISSUE THREAD

**Issue by FayK12** [hapifhir/hapi-fhir-jpaserver-starter#91]
I've followed the steps to 'Deploy with docker compose'. Both times the build has failed but due to different reasons. First time it failed at 'HAPI FHIR - Command Line Client - API .' because it couldn't find the mysql connector (even though it was on the central maven repo). The second time it failed, it failed before reaching the first failure point, namely 'HAPI FHIR - fhirtest.uhn.ca Deployable WAR'.
Both times however, the build via docker compose is taking over 2h. Has anyone else had this issue where it takes so long?

**Comment by citizenrich** [comment]
I am also seeing build failures using the provided Dockerfile.

**Comment by seanmcilvenna** [comment]
I just re-built the v4.1.0, v4.2.0 and v5.0.0 tags. They are all on [docker hub](https://hub.docker.com/repository/docker/hapiproject/hapi). I did not encounter any errors like this for these tags. I did, however, encounter errors for the v4.0.0 tag...

**Comment by seanmcilvenna** [comment]
I've also updated the readme on using the tags from [docker hub](https://hub.docker.com/repository/docker/hapiproject/hapi). Perhaps you'd find it easier to re-use one of the pre-built tags?

**Comment by citizenrich** [comment]
Thanks, I've confirmed builds work inside containers for master and v5. Also, I don't know how widespread the use of the hapi official images are, but adding the `v` breaks docker-compose files and kubernetes manifests.
