### ISSUE TITLE
Can't build with hapi-fhir r4.2.0

### ISSUE THREAD

**Issue by jeffeastman** [hapifhir/hapi-fhir-jpaserver-starter#92]
I checked-out hapi-fhir r4.2.0 on my machine and built it just fine. Then I switched the hapi-fhir-jpaserver-starter pom to reference that tag instead of r4.0.0. It will not build, throwing this error:

`[ERROR] Failed to execute goal on project hapi-fhir-jpaserver-starter: Could not resolve dependencies for project ca.uhn.hapi.fhir.demo:hapi-fhir-jpaserver-starter:war:4.2.0: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir-jpaserver-elasticsearch:jar:4.2.0 in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
`

**Comment by patrick-werner** [comment]
jpaserver is already set to use hapi-fhir 4.2.0 as parent. What did you change exactly from which value to what new value?

**Comment by jeffeastman** [comment]
I had cloned jpaserver and modified the pom to reference hapi-fhir r4.2.0 vs r4.0.0. Since then, however, I've downloaded the jpaserver r4.2.0 sources and am able to run that out of the box so I'm closing this ticket as my pilot error somewhere.
