### ISSUE TITLE
NULL not allowed for column

### ISSUE THREAD

**Issue by dletter** [hapifhir/hapi-fhir-jpaserver-starter#93]
My build is fully up, and mostly working, but I am seeing this now:
" Warning!

Error: HTTP 500 Server Error: NULL not allowed for column "SEARCH_LAST_RETURNED"; SQL statement: insert into HFJ_SEARCH (CREATED, SEARCH_DELETED, EXPIRY_OR_NULL, FAILURE_CODE, FAILURE_MESSAGE, LAST_UPDATED_HIGH, LAST_UPDATED_LOW, NUM_BLOCKED, NUM_FOUND, PREFERRED_PAGE_SIZE, RESOURCE_ID, RESOURCE_TYPE, SEARCH_PARAM_MAP, SEARCH_QUERY_STRING, SEARCH_QUERY_STRING_HASH, SEARCH_TYPE, SEARCH_STATUS, TOTAL_COUNT, SEARCH_UUID, OPTLOCK_VERSION, PID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23502-200]"

I have no diffs in the project other than changes to some graphics files, the git pull from this project is current.

Is there something that needs to be run separately to update the tables HAPI natively uses before spinning up with "mvn jetty:run" in the hapi-fhir-jpaserver-starter directory, after a git pull updates things?

**Comment by jvitrifork** [comment]
@dletter is this still an issue for you?

**Comment by dletter** [comment]
I've gotten past this issue since then, thank you.
