### ISSUE TITLE
docker-compose fails in master and rel_5_0_0

### ISSUE THREAD

**Issue by hkong2** [hapifhir/hapi-fhir-jpaserver-starter#94]
`docker-compose up -d --build` fails in the 2nd stage when building `HAPI FHIR Structures - FHIR R4 5.0.0-SNAPSHOT [11/53]`

```[ERROR] COMPILATION ERROR : 
[INFO] ------------------
[ERROR] /tmp/hapi-fhir/hapi-fhir-structures-r4/src/test/java/ca/uhn/fhir/rest/client/GenericClientR4Test.java:[1604,85] error: cannot find symbol
  symbol:   variable TimeZone
  location: class GenericClientR4Test
```

I've tried both `master` and `rel_5_0_0`.  Running `Docker Desktop for Mac` v2.2.0 on OS X Mojave, Docker version 19.03.8, docker-compose version 1.25.4.

**Comment by vinaymcp** [comment]
I am also facing the same issue.

**Comment by jamesagnew** [comment]
Fixed in https://github.com/jamesagnew/hapi-fhir/commit/33b8e82f791b482ec5795fc52a33fa889a9daa11
